"use client";
import {useEffect,useState} from "react";

type Check={field:string;expected:string|number|null;actual:string|number|null;delta:number|null;status:string;origin:string;source_decimal_places:number|null};
type Leg={status:string;reason?:string;checks:Check[]};
type Trade={event_id:string;symbol:string;signal_date:string;entry_date:string;entry_price:number;baseline:{exit_date:string;exit_price:number;exit_reason:string;return:number;stop:number;r_multiple:number};accounting:Leg;cache_replay:Leg};
export type ComparisonReport={source:{as_of:string;sha256:string;git_commit:string};selection:{count:number;total_events:number;eligible_policy_count:number;excluded_other_or_missing_policy:number;outside_fixed_limit:number};engine:{version:string;adapter_sha256:string};input_sha256:string;cache_key:string|null;events:Trade[];summary:Record<string,Record<string,number>>;content_fingerprint:string};
const labels:Record<string,string>={entry_price:"入场价",exit_price:"退出价",gross_return:"毛收益",r_multiple:"R倍数（本站派生）",fees:"零费用假设",net_return_zero_cost_scenario:"零成本场景收益",quantity:"单位数量假设",entry_slot:"入场成交序号",exit_slot:"退出成交序号",closed_status:"成交闭合",entry_order_side:"买入方向",exit_order_side:"卖出方向",unit_pnl:"单位损益",entry_date:"入场日",entry:"入场价",stop:"止损价",target:"目标价",exit_date:"退出日",exit_reason:"退出原因",holding_sessions:"持有交易日",return:"毛收益",status:"状态"};
const state=(s:string)=>s==="match"?"一致":s==="difference"?"有差异":"不可用";
const number=(v:string|number|null)=>v===null||v===undefined?"—":typeof v==="number"?String(v):v;

export function ComparisonView({reports}:{reports:ComparisonReport[]}){
 const [index,setIndex]=useState(reports.length-1),[selected,setSelected]=useState("");
 const report=reports[index];const row=report.events.find(r=>r.event_id===selected)??report.events[0];
 const pricesMatch=report.events.filter(r=>r.accounting.checks.filter(c=>["entry_price","exit_price"].includes(c.field)).length===2&&r.accounting.checks.filter(c=>["entry_price","exit_price"].includes(c.field)).every(c=>c.status==="match")).length;
 return <div className="tradeComparison"><header className="svPanel"><small>VectorBT {report.engine.version} · 真实旧记录 · 工程对账</small><h2>20笔成交，逐项核对</h2><p>这不是完整回测或新策略收益验证。旧冻结退出是输入；VectorBT没有重新决定买卖。真实费用与数量缺失，本次使用每笔1单位、零费用和零滑点假设，不代表实际净收益。</p><label>查看运行 <select value={index} onChange={e=>{setIndex(Number(e.target.value));setSelected("")}}>{reports.map((r,i)=><option value={i} key={i}>{r.cache_key==="eodhd-history-v1-33293559230"?"较早行情版本（A0）":r.cache_key==="eodhd-history-v1-34184997473"?"近期行情版本":"本地成交记账（未恢复行情）"}</option>)}</select></label></header>
 <div className="tradeComparisonSummary"><article><small>固定样本</small><strong>{report.events.length}笔</strong><span>{report.events[0]?.signal_date} 起 · 旧政策最早20条</span></article><article><small>成交价格一致</small><strong>{pricesMatch}/{report.events.length}</strong><span>仅核对冻结入退场价 · 每笔1单位假设</span></article><article><small>全部记账字段一致／有差异</small><strong>{report.summary.accounting.match??0} / {report.summary.accounting.difference??0}</strong><span>不可用 {report.summary.accounting.unavailable??0} 笔 · 零费用假设</span></article></div>
 <p className="tradeComparisonNotice">价格不一致与记账数值差异分开统计。当前微小收益／R差异可能与原价格保存精度有关，具体原因仍待核实；没有改变比对精度，也未将差异抹成通过。真实净收益不可用，表中的零成本收益只是工程场景。</p>
 <section className="svPanel"><h3>两项检查分别看</h3><p><b>① 旧执行算法在恢复行情上的重放：</b>{report.cache_key?`一致 ${report.summary.cache_replay.match??0}，差异 ${report.summary.cache_replay.difference??0}，不可用 ${report.summary.cache_replay.unavailable??0}`:"本次未恢复行情，20笔均不可用；等待精确A0及当前缓存研究作业。"}</p><p><b>② VectorBT成交记账：</b>按原成交输入核对价格、单位数量、毛收益和零费用场景；R由本站按冻结风险另外计算。</p><p>两者都不是独立验证退出算法。MFE／MAE与真实费用后的净收益不可用；原账本未保留原始行情指纹，即便重放一致也不能证明历史修订完全相同。</p></section>
 <section className="svPanel"><h3>逐笔记录 · 点击查看差异</h3><div className="tradeComparisonTable"><table><thead><tr><th>事件／股票</th><th>信号／入场</th><th>入场价 → 退出价</th><th>原退出</th><th>记账／路径重放</th></tr></thead><tbody>{report.events.map(r=><tr key={r.event_id} data-selected={row?.event_id===r.event_id}><td><button onClick={()=>setSelected(r.event_id)}>{r.symbol}</button><small>{r.event_id}</small></td><td>{r.signal_date}<small>{r.entry_date}</small></td><td>{r.entry_price} → {r.baseline.exit_price}</td><td>{({stop:"触及止损",stop_gap:"跳空止损",target:"达到目标",time_40d:"持满40个交易日"} as Record<string,string>)[r.baseline.exit_reason]??r.baseline.exit_reason}<small>{r.baseline.exit_date}</small></td><td><span data-state={r.accounting.status}>{state(r.accounting.status)}</span><small>{state(r.cache_replay.status)}</small></td></tr>)}</tbody></table></div></section>
 {row&&<section className="svPanel"><h3>{row.symbol} · 原值、引擎值与差异</h3>{([['accounting','VectorBT成交记账'],['cache_replay','原算法在缓存行情上重放']] as const).map(([key,title])=><div key={key}><h4>{title} · {state(row[key].status)}</h4>{row[key].reason&&<p>不可用原因：{row[key].reason}</p>}<div className="tradeComparisonTable"><table><thead><tr><th>字段</th><th>旧值／假设</th><th>核对值</th><th>原始差值</th><th>结论</th></tr></thead><tbody>{row[key].checks.map(c=><tr key={c.field}><td>{labels[c.field]??c.field}<small>{c.source_decimal_places===null?"精确比对":`按原保存精度 ${c.source_decimal_places} 位比对`}</small></td><td>{number(c.expected)}</td><td>{number(c.actual)}</td><td>{number(c.delta)}</td><td data-state={c.status}>{state(c.status)}</td></tr>)}</tbody></table></div></div>)}</section>}
 <details className="svPanel"><summary>样本、来源与下一步</summary><p>账本截止 {report.source.as_of}。共 {report.selection.total_events} 条，旧执行政策匹配 {report.selection.eligible_policy_count} 条；其他／无政策 {report.selection.excluded_other_or_missing_policy} 条，固定20条以外 {report.selection.outside_fixed_limit} 条。不按盈亏或对账结果换样本，已固定事件缺失也保留。</p><p>政策：支撑下5%与入场下10%取更高止损，2R目标，最多40交易日，同日冲突止损优先。未实施讨论中的新2%缓冲或半年新鲜度。</p><p>本页缓存运行已恢复指定历史缓存，核对固定20事件的日期、成交与复权指纹。完整缓存先恢复到隔离环境，仅处理固定样本；没有重新下载多年行情或重跑门票／评分。</p><p>来源提交 {report.source.git_commit}<br/>冻结输入 {report.input_sha256}<br/>报告 {report.content_fingerprint}</p><p><a href="/vectorbt-comparison.json" download>下载本页派生对账JSON</a> · <a href="https://github.com/polakowo/vectorbt/blob/v1.1.0/LICENSE.md" target="_blank" rel="noreferrer">VectorBT 1.1.0 许可</a></p></details>
 </div>;
}

export default function Comparison(){
 const [reports,setReports]=useState<ComparisonReport[]|null>(null),[failed,setFailed]=useState(false);
 useEffect(()=>{let active=true;fetch('/vectorbt-comparison.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('missing');return r.json()}).then(d=>{if(!Array.isArray(d.reports)||!d.reports.length)throw Error('invalid');if(active)setReports(d.reports)}).catch(()=>{if(active)setFailed(true)});return()=>{active=false}},[]);
 return reports?<ComparisonView reports={reports}/>:<section className="svPanel">{failed?"对账报告暂不可用，未将缺失当作通过。":"正在读取已运行的逐笔对账报告…"}</section>;
}
