"use client";
import {TrackerShell} from "../tracker-ui";
import report from "../../../../../research/backtest/output/v2-summary.json";
const pct=(x:number|null)=>x==null?"—":`${x.toFixed(2)}%`;
export default function BacktestV2(){const rows=report.combinations,stopRows=report.stop_definitions.map(s=>rows.find(x=>x.stop_id===s.id&&x.target_r===2)!);return <TrackerShell active="Strategy Backtest" title="Backtest V2 / Stop & Risk-Reward" subtitle="冻结 V1 信号与 Entry，只比较六种 Stop × 四种固定 TP；不进入 production。"><section className="btNotice"><b>V2 是独立风险实验，不是参数推荐。</b><span>{report.source.signals.toLocaleString()} 条 V1 信号 · 40 bars 上限 · 同 K 线 Stop 优先</span></section>
<section className="btAnswers"><article><small>最少被波动洗掉</small><b>Support −5%</b><p>2R Stop-out {pct(stopRows.find(x=>x.stop_id==="support_5pct")!.groups.all.stop_out_rate)}；代价是风险距离和持仓时间更大。</p></article><article><small>跨时期稳定性</small><b>宽 Stop 相对较稳</b><p>Support −5% 的 1R–3R 在开发、2025、2026 均为正 Expectancy / PF&gt;1；不是自动选择。</p></article><article><small>更宽止损代价</small><b>有明显风险交换</b><p>平均风险距离随 buffer 扩大；Max DD 并未单调改善，不能只看胜率。</p></article><article><small>Early vs Confirmed</small><b>Confirmed 更稳</b><p>多数 Stop/TP 下 Confirmed PF 高于 Early Watch；宽止损时差距缩小。</p></article></section>
<section className="btPanel"><header><div><small>FULL MATRIX · ALL SIGNALS</small><h2>六种 Stop × 四种 TP</h2></div><span>Expectancy = 平均收益；Average R = 平均 R multiple</span></header><div className="btV2Table"><div><b>Stop / TP</b><span>Win</span><span>PF</span><span>Expect.</span><span>Avg R</span><span>Stop-out</span><span>Max DD</span><span>Bars</span><span>MFE</span><span>MAE</span></div>{rows.map(x=>{const g=x.groups.all;return <div key={`${x.stop_id}-${x.target_r}`}><b>{x.stop_label} · {x.target_r}R</b><span>{pct(g.win_rate)}</span><span>{g.profit_factor?.toFixed(3)??"—"}</span><span>{pct(g.expectancy_pct)}</span><span>{g.average_r?.toFixed(3)??"—"}</span><span>{pct(g.stop_out_rate)}</span><span>{pct(g.max_drawdown_pct)}</span><span>{g.average_holding_bars?.toFixed(1)}</span><span>{pct(g.mfe_pct)}</span><span>{pct(g.mae_pct)}</span></div>})}</div></section>
<section className="btPanel"><header><div><small>GROUP COMPARISON · 2R</small><h2>Early Watch / Confirmed / 严格长期趋势</h2></div></header><div className="btV2Groups">{stopRows.map(x=><article key={x.stop_id}><b>{x.stop_label}</b>{(["early_watch","confirmed","strict_long_trend"] as const).map(k=><p key={k}><span>{k==="early_watch"?"Early Watch":k==="confirmed"?"Confirmed":"严格趋势"}</span><strong>PF {x.groups[k].profit_factor} · Exp {pct(x.groups[k].expectancy_pct)} · Stop {pct(x.groups[k].stop_out_rate)}</strong></p>)}</article>)}</div></section>
<section className="btPanel"><header><div><small>PERIOD ROBUSTNESS · 2R</small><h2>开发期 / 2025验证 / 2026前向</h2></div></header><div className="btV2Groups">{stopRows.map(x=><article key={x.stop_id}><b>{x.stop_label}</b>{Object.entries(x.periods).map(([k,v])=><p key={k}><span>{k==="development"?"开发期":k==="validation_2025"?"2025验证":"2026前向"}</span><strong>PF {v.profit_factor} · {pct(v.expectancy_pct)}</strong></p>)}</article>)}</div></section>
<section className="btLimits"><b>阅读限制与执行审计</b><p>ATR 只计算到信号日；Entry 与 V1 下一交易日 Open 逐条核对；风险距离≤0.1%的 scenario 标为不可执行。Max Drawdown 是非重叠40日等权 cohort 诊断，不是资金约束组合。</p>{report.methodology.map(x=><span key={x}>{x}</span>)}</section><a className="btResearchLink" href="/zh/watch/resonance/strategy-backtest"><span>V1</span><b>返回 Tracker Backtest V1</b><small>查看信号、Ranking、趋势过滤与历史表现。</small></a></TrackerShell>}
