"use client";
import {TrackerShell} from "../tracker-ui";
import report from "../../../../../research/backtest/output/market-regime-v1.json";
const pct=(x:number|null)=>x==null?"—":x.toFixed(2)+"%";
const labels:Record<string,string>={development:"2010–2024 开发期",validation_2025:"2025 验证期",forward_2026:"2026 前向期"};
export default function MarketRegime(){const c=report.current;return <TrackerShell active="MACD研究" title="Market Regime / 大盘环境" subtitle="验证市场环境能否改善冻结的 Long benchmark；当前不参与 production 过滤或仓位。">
<section className="mrHero"><div><small>RESEARCH AS OF · {c.date}</small><h2>{c.regime}</h2><p>Score {c.score}/100</p></div><div className="mrScore"><i style={{width:String(c.score)+"%"}}/><span>Risk-Off &lt;40</span><span>Neutral 40–65</span><span>Risk-On ≥65</span></div><aside><b>研究缓存日期</b><strong>{c.date}</strong><span>不冒充 production 最新日期</span></aside></section>
<section className="btAnswers"><article><small>Risk-On 是否提升 benchmark</small><b>没有</b><p>PF {report.by_regime["Risk-On"].profit_factor}，Expectancy {pct(report.by_regime["Risk-On"].expectancy_pct)}；低于严格定义全样本。</p></article><article><small>Neutral 是否值得做 Long</small><b>仍有正值，但不稳定</b><p>全期 PF {report.by_regime.Neutral.profit_factor}；开发期仅 {report.by_period_regime.development.Neutral.profit_factor}。</p></article><article><small>Risk-Off 是否拖累</small><b>没有一致结论</b><p>开发期异常较强，2025 PF 仅 {report.by_period_regime.validation_2025["Risk-Off"].profit_factor}，样本很少。</p></article><article><small>只做 Risk-On</small><b>样本 −{pct(report.answers.risk_on_vs_all.sample_reduction_pct)}</b><p>PF 变化 {report.answers.risk_on_vs_all.pf_change}；Expectancy {pct(report.answers.risk_on_vs_all.expectancy_change_pct)}。</p></article></section>
<section className="mrGrid">{(["spy","qqq"] as const).map(k=><article className="btPanel" key={k}><header><div><small>TREND + MOMENTUM</small><h2>{k.toUpperCase()} · USD {c[k].close}</h2></div></header><div className="mrIndex"><span>{c[k].above_50dma?"✓":"×"} Close &gt; 50DMA</span><span>{c[k].above_200dma?"✓":"×"} Close &gt; 200DMA</span><span>{c[k].dma50_above_200?"✓":"×"} 50DMA &gt; 200DMA</span><span>{c[k].dma200_slope_positive?"✓":"×"} 200DMA slope</span><span>Daily · {c[k].daily_macd}</span><span>Daily histogram · {c[k].daily_histogram}</span><span>Weekly · {c[k].weekly_macd}</span><span>Weekly histogram · {c[k].weekly_histogram}</span></div></article>)}</section>
<section className="btPanel"><header><div><small>BREADTH · {c.breadth_score}/30</small><h2>Market Breadth</h2></div><span>{c.breadth.eligible} 个当日有效历史</span></header><div className="mrBreadth">{[["Above 50DMA",c.breadth.above_50dma_pct],["Above 200DMA",c.breadth.above_200dma_pct],["Bullish Trend",c.breadth.bullish_trend_pct],["Bearish Trend",c.breadth.bearish_trend_pct]].map(([n,v])=><article key={String(n)}><b>{n}</b><strong>{pct(Number(v))}</strong><i><em style={{width:String(v)+"%"}}/></i></article>)}</div></section>
<section className="btPanel"><header><div><small>RECENT REGIME PATH</small><h2>最近120个交易日</h2></div></header><div className="mrTimeline">{report.timeline.map(x=><i key={x.date} className={x.regime.replace("-","").toLowerCase()} title={x.date+" · "+x.regime+" · "+x.score}/>)}</div><div className="mrLegend"><span>Risk-Off</span><span>Neutral</span><span>Risk-On</span></div></section>
<section className="btPanel"><header><div><small>BACKTEST BY REGIME</small><h2>冻结 benchmark 按信号日环境分组</h2></div><span>Confirmed + 严格趋势 + Support −5% + 2R</span></header><div className="mrTable"><div><b>Regime</b><span>Samples</span><span>Win</span><span>PF</span><span>Expectancy</span><span>Avg R</span><span>Max DD</span><span>Stop-out</span></div>{(["All","Risk-On","Neutral","Risk-Off"] as const).map(k=>{const m=report.by_regime[k];return <div key={k}><b>{k}</b><span>{m.samples}</span><span>{pct(m.win_rate)}</span><span>{m.profit_factor}</span><span>{pct(m.expectancy_pct)}</span><span>{m.average_r}</span><span>{pct(m.max_drawdown_pct)}</span><span>{pct(m.stop_out_rate)}</span></div>})}</div></section>
<section className="btPanel"><header><div><small>TIME CONSISTENCY</small><h2>三个时期方向检查</h2></div></header><div className="mrPeriods">{Object.entries(report.by_period_regime).map(([period,groups])=><article key={period}><b>{labels[period]}</b>{Object.entries(groups).map(([regime,m])=><p key={regime}><span>{regime} · n={m.samples}</span><strong>PF {m.profit_factor??"—"} · Exp {pct(m.expectancy_pct??null)}</strong></p>)}</article>)}</div></section>
<section className="btLimits"><b>结论：Market Regime V1 暂时没有验证为 Long filter</b><p>PF 1.159 / +0.694% 属于 V2 严格趋势组（包含两个状态）；本页严格执行 Confirmed + 严格趋势后，全样本为 PF {report.by_regime.All.profit_factor} / {pct(report.by_regime.All.expectancy_pct)}。Risk-On 没有改善，Risk-Off 也没有跨时期保持一致，因此不进入 production。</p>{report.limitations.map(x=><span key={x}>{x}</span>)}</section>
</TrackerShell>}
