"use client";
import {TrackerShell} from "../tracker-ui";
import report from "../../../../../research/backtest/output/factor-attribution-v1.json";
const pct=(x:number|null|undefined)=>x==null?"—":x.toFixed(2)+"%";
const periodLabels:Record<string,string>={development:"2010–2024",validation_2025:"2025",forward_2026:"2026"};
export default function FactorAttribution(){return <TrackerShell active="MACD研究" title="Factor Attribution / 因子贡献" subtitle="冻结 Long benchmark 的有/无因子诊断；不改变 production 权重、Ranking 或信号。">
 <section className="btNotice"><b>结论：高多因子分与高 Tracker Rank 衡量的不是同一件事。</b><span>{report.benchmark.metrics.samples} 个 Confirmed + 严格趋势历史交易</span></section>
 <section className="btAnswers"><article><small>稳定正贡献</small><b>暂时没有</b><p>没有因子同时满足三阶段同向、且验证与前向样本充足。</p></article><article><small>正向候选</small><b>看涨吞没</b><p>三段方向均为正，但2025只有18个、2026只有8个命中，证据不足。</p></article><article><small>可能拖累</small><b>底部放量 / 突破回踩</b><p>全样本 Expectancy delta 分别为 −0.491 与 −0.479 个百分点。</p></article><article><small>禁止动作</small><b>不调权重</b><p>这是观察性 attribution，不是因果证明，也没有自动搜索组合。</p></article></section>
 <section className="btPanel"><header><div><small>WHY RANK DIVERGES</small><h2>Tracker Rank 与 Multi-Factor Score 的排序来源不同</h2></div></header><div className="faRankGrid">{report.rank_diagnosis.map(x=><article key={x.bucket}><small>{x.bucket}</small><b>PF {x.metrics.profit_factor}</b><span>Expectancy {pct(x.metrics.expectancy_pct)}</span><p>多因子均分 {x.mean_multifactor_score}<br/>Tracker层级分 {x.mean_tracker_score}<br/>对齐多头层 {x.mean_aligned_long_layers}</p></article>)}</div><p className="btCaution">Rank 1–3 的 Tracker 层级分更高，但多因子均分低于 Rank 7–10。现有 Rank 优先体现 MACD/多周期层对齐，并非历史收益排序。</p></section>
 <section className="btPanel"><header><div><small>SCORE DIAGNOSTIC</small><h2>多因子分组</h2></div></header><div className="faRankGrid">{report.score_diagnosis.map(x=><article key={x.bucket}><small>{x.bucket}</small><b>PF {x.metrics.profit_factor}</b><span>Expectancy {pct(x.metrics.expectancy_pct)}</span><p>n={x.metrics.samples} · 平均 Rank {x.mean_rank}</p></article>)}</div></section>
 <section className="btPanel"><header><div><small>WITH vs WITHOUT</small><h2>逐因子真实贡献</h2></div><span>Average Return 与 Expectancy 均为平均交易收益</span></header><div className="faTable"><div><b>因子</b><span>状态</span><span>有/无样本</span><span>Win Δ</span><span>PF Δ</span><span>Expectancy Δ</span></div>{report.factor_attribution.map(x=><div key={x.factor}><b>{x.factor}</b><span>{x.status}</span><span>{x.overall.with.samples} / {x.overall.without.samples}</span><span>{pct(x.overall.delta.win_rate)}</span><span>{x.overall.delta.profit_factor}</span><span>{pct(x.overall.delta.expectancy_pct)}</span></div>)}</div></section>
 <section className="btPanel"><header><div><small>PERIOD CONSISTENCY</small><h2>2010–2024 / 2025 / 2026</h2></div></header><div className="faFactors">{report.factor_attribution.filter(x=>x.factor!=="日线MACD近5日金叉").map(x=><article key={x.factor}><header><b>{x.factor}</b><span>{x.status}</span></header>{Object.entries(x.periods).map(([period,v])=><p key={period}><span>{periodLabels[period]} · n={v.with.samples}</span><strong>PF Δ {v.delta.profit_factor} · Exp Δ {pct(v.delta.expectancy_pct)}</strong></p>)}</article>)}</div></section>
 <section className="btPanel"><header><div><small>PREDEFINED PAIRS ONLY</small><h2>值得继续研究的语义组合</h2></div><span>没有全排列或最佳组合搜索</span></header><div className="faRankGrid">{report.predefined_combinations.map(x=><article key={x.name}><small>{x.factors.join(" + ")}</small><b>{x.name}</b><span>n={x.comparison.with.samples} · PF Δ {x.comparison.delta.profit_factor}</span><p>Expectancy Δ {pct(x.comparison.delta.expectancy_pct)}<br/>{x.note}</p></article>)}</div></section>
 <section className="btLimits"><b>诊断边界</b>{report.limitations.map(x=><span key={x}>{x}</span>)}</section>
 </TrackerShell>}
