"use client";
import {useEffect,useMemo,useState} from "react";
import {TrackerShell,useTracker} from "./tracker-ui";

type IndustryTheme={theme_id:string;name:string;state:string;etf_context?:{favorable_setup:boolean;confirming_funds:string[]}};
type Classification={sector?:string;industry_group?:string;industry?:string;market_cap?:string};
type IndustryLink={theme_id:string;state:string;etf_context?:IndustryTheme["etf_context"]};
type IndustryReport={as_of:string;future_data_used:boolean;themes:IndustryTheme[];ticker_context:Record<string,IndustryLink[]>;classification_by_ticker?:Record<string,Classification>};
type FactorState={factor_id:string;available:boolean;hit:boolean;recent_hit:boolean;bars_since_hit:number|null};
type FactorSnapshot={as_of:string;future_data_used:boolean;symbols:{symbol:string;factors:FactorState[]}[]};
type FactorRegistry={registry_version:string;factor_count:number;factors:{id:string;name_zh:string}[]};
type MarketFund={ticker:string;return_20d:number;above_ema50:boolean};
type MarketReport={as_of:string;market_temperature:{state:string;score:number;max_score:number};layers:{trend:{state:string};breadth:{state:string};risk_appetite:{state:string}};ratios:Record<string,number>;funds:MarketFund[]};
type RareSignal={symbol:string;price:number;level:string;total_score:number;official_score:number;experimental_observational_score:number;components:string[];risks:string[]};
type RareReport={signals:RareSignal[]};
type V2Signal={symbol:string;price:number;technical_score:number;market_adjustment:number;industry_adjustment:number;final_priority:number;reasons:string[];industry_states:string[]};
type UnifiedV2={coverage:{start:string;end:string;sessions:number};days:{date:string;ranking:V2Signal[]}[]};
type SignalCase={symbol:string;first_seen_date:string;lifecycle:string;latest_current_status:string;forward:{elapsed_sessions:number;status:string}};
type SignalHistory={cases:SignalCase[]};
type DecisionMetric={samples:number;win_rate:number;profit_factor:number;expectancy_pct:number;median_return_pct:number|null};
type DecisionItem={name:string;role?:string;verdict:string;metrics?:DecisionMetric;note:string};
type DecisionSummary={production_status:string;plain_summary:string;usable:DecisionItem[];watch:DecisionItem[];avoid:DecisionItem[];method_note:string;coverage:{start:string;end:string;audited_events:number;primary_events:number}};

const stateLabel:Record<string,string>={Leadership:"领先","Pullback Watch":"回调观察",Recovery:"修复",Neutral:"中性",Unavailable:"数据不足"};
const json=(path:string)=>fetch(path,{cache:"no-store"}).then(x=>x.ok?x.json():null);
const pct=(value:number|undefined)=>value===undefined?"—":`${value>=0?"+":""}${(value*100).toFixed(1)}%`;

export default function Overview(){
 const tracker=useTracker();
 const [industry,setIndustry]=useState<IndustryReport|null>(null),[snapshot,setSnapshot]=useState<FactorSnapshot|null>(null),[registry,setRegistry]=useState<FactorRegistry|null>(null),[market,setMarket]=useState<MarketReport|null>(null),[history,setHistory]=useState<SignalHistory|null>(null),[rare,setRare]=useState<RareReport|null>(null),[unified,setUnified]=useState<UnifiedV2|null>(null),[decision,setDecision]=useState<DecisionSummary|null>(null),[selected,setSelected]=useState<string|null>(null);
 useEffect(()=>{Promise.all([json("/industry-radar.json"),json("/daily-factor-snapshot.json"),json("/factor-registry.json"),json("/market-etf-watch.json"),json("/signal-history.json"),json("/rare-opportunity-radar.json"),json("/unified-v2-rankings.json"),json("/decision-summary.json")]).then(([i,s,r,m,h,o,u,d])=>{setIndustry(i);setSnapshot(s);setRegistry(r);setMarket(m);setHistory(h);setRare(o);setUnified(u);setDecision(d)})},[]);
 const themes=useMemo(()=>Object.fromEntries((industry?.themes??[]).map(x=>[x.theme_id,x])),[industry]);
 const factors=useMemo(()=>Object.fromEntries((registry?.factors??[]).map(x=>[x.id,x.name_zh])),[registry]);
 const factorByTicker=useMemo(()=>Object.fromEntries((snapshot?.symbols??[]).map(x=>[x.symbol,x])),[snapshot]);
 const casesByTicker=useMemo(()=>{const out:Record<string,SignalCase[]>={};for(const item of history?.cases??[])(out[item.symbol]??=[]).push(item);return out},[history]);
 const latestV2=unified?.days.at(-1),v2Current=!!latestV2&&!!tracker&&latestV2.date===tracker.as_of;
 const opportunities=useMemo(()=>v2Current&&latestV2?latestV2.ranking.slice(0,8).map(x=>({symbol:x.symbol,price:x.price,level:"V2 新模型",total_score:x.final_priority,official_score:0,experimental_observational_score:x.technical_score,components:x.reasons,risks:[],technical_score:x.technical_score,industry_adjustment:x.industry_adjustment,market_adjustment:x.market_adjustment})):(rare?.signals?.length?rare.signals.slice(0,8):(tracker?.macd_buy_top10??[]).slice(0,8).map(x=>({symbol:x.symbol,price:x.price,level:"技术观察",total_score:0,official_score:0,experimental_observational_score:0,components:[],risks:[]}))),[latestV2,rare,tracker,v2Current]);
 const opportunityByTicker=useMemo(()=>Object.fromEntries(opportunities.map(x=>[x.symbol,x])),[opportunities]);
 const activeSymbol=selected??opportunities[0]?.symbol;
 const chosen=(activeSymbol&&opportunityByTicker[activeSymbol])||opportunities[0];
 const classification=chosen?industry?.classification_by_ticker?.[chosen.symbol]:undefined;
 const links=chosen?(industry?.ticker_context[chosen.symbol]??[]):[];
 const evidence=chosen?(factorByTicker[chosen.symbol]?.factors??[]).filter(x=>x.available&&(x.hit||x.recent_hit)).sort((a,b)=>(Number(b.hit)-Number(a.hit))||((a.bars_since_hit??99)-(b.bars_since_hit??99))).slice(0,6):[];
 const cases=chosen?(casesByTicker[chosen.symbol]??[]).sort((a,b)=>b.first_seen_date.localeCompare(a.first_seen_date)):[],latestCase=cases[0];
 const funds=Object.fromEntries((market?.funds??[]).map(x=>[x.ticker,x]));
 const marketReference=classification?.market_cap?.match(/Nano|Micro|Small/i)?"IWM":classification?.sector==="Information Technology"?"QQQ":"SPY",reference=funds[marketReference];
 const risk=market?.market_temperature.state==="防守"?{label:"高风险",tone:"high",action:"保护仓位，暂缓新建仓"}:market?.market_temperature.state==="风险偏好"?{label:"风险较低",tone:"low",action:"可正常研究，仍等回撤入场"}:{label:"中等风险",tone:"medium",action:"精选机会，不追高"};
 const marketStory=!market?"正在载入市场数据。":market.layers.trend.state!=="supportive"?"指数趋势转弱，今天优先保护仓位。":market.layers.breadth.state!=="broad"?"大盘趋势还在，但上涨集中在少数股票：能做，但要精选。":"指数趋势与市场广度同步，环境对多头研究较友好。";
 const synced=!!tracker&&!!industry&&!!snapshot&&!!market&&tracker.as_of===snapshot.as_of&&tracker.as_of===market.as_of&&!snapshot.future_data_used&&!industry.future_data_used;
 const smallCapLeading=(market?.ratios?.["小盘相对大盘"]??0)>0;
 const segmentCards=[["大盘股","SPY",funds.SPY?.above_ema50?"支持":"谨慎",funds.SPY?.above_ema50?"positive":"negative"],["科技成长","QQQ",funds.QQQ?.above_ema50?"偏强":"谨慎",funds.QQQ?.above_ema50?"positive":"negative"],["小盘股","IWM",smallCapLeading?"参与":"落后",smallCapLeading?"positive":"negative"],["市场广度","RSP",market?.layers.breadth.state==="broad"?"广泛":"分化",market?.layers.breadth.state==="broad"?"positive":"warning"]] as const;
 const hotThemes=(industry?.themes??[]).filter(x=>x.state==="Leadership"||x.state==="Recovery").slice(0,3);

 return <TrackerShell active="今日研究总览" title="今日总览" subtitle="市场、行业与个股机会" overview>{tracker&&<div className="marketFirstHome">
  <section className="overviewHero" data-tone={risk.tone}><div className="overviewVerdict"><header><span><i/>最新完整收盘 · {tracker.as_of}</span><em>{synced?"数据已核验":"数据待核验"}</em></header><small>TODAY&apos;S DECISION</small><h1>{market?.market_temperature.state??"等待"} <b>· {risk.label}</b></h1><p>{marketStory}</p><strong>{risk.action}</strong></div><div className="overviewScore"><span>市场温度</span><b>{market?.market_temperature.score??"—"}<small>/{market?.market_temperature.max_score??5}</small></b><p>环境只调整优先级和仓位，不改写个股技术事实。</p></div><div className="overviewLayers"><article><small>01 · 趋势</small><b>{market?.layers.trend.state==="supportive"?"支持多头":"趋势转弱"}</b><span>SPY 20日 {pct(funds.SPY?.return_20d)}</span></article><article><small>02 · 广度</small><b>{market?.layers.breadth.state==="broad"?"多数股票参与":"上涨集中"}</b><span>等权相对 {pct(market?.ratios?.["等权相对市值权重"])}</span></article><article><small>03 · 风险偏好</small><b>{market?.layers.risk_appetite.state==="risk_seeking"?"资金愿意冒险":"风险偏好不足"}</b><span>成长相对 {pct(market?.ratios?.["成长相对大盘"])}</span></article></div></section>
  <section className="marketTape" aria-label="市场分层">{segmentCards.map(([name,ticker,label,tone])=><article key={ticker} data-tone={tone}><div><small>{name}</small><b>{ticker}</b></div><strong>{label}</strong><span>20日 {pct(funds[ticker]?.return_20d)}</span></article>)}</section>
  {decision&&<section className="productionEvidence"><header><div><small>01 · LATEST AUDITED RESEARCH</small><h2>现在能用什么</h2><p>{decision.plain_summary}</p></div><mark>已同步至 {decision.coverage.end}</mark></header><div className="evidenceColumns"><div><h3>✓ 保留与观察</h3>{decision.usable.map(x=><article key={x.name}><header><div><b>{x.name}</b><span>{x.role}</span></div>{x.metrics&&<strong>{x.metrics.win_rate.toFixed(1)}%<small>2026胜率</small></strong>}</header>{x.metrics&&<div><span>样本 <b>{x.metrics.samples}</b></span><span>PF <b>{x.metrics.profit_factor.toFixed(2)}</b></span><span>期望 <b>{x.metrics.expectancy_pct>0?"+":""}{x.metrics.expectancy_pct.toFixed(2)}%</b></span></div>}<p>{x.note}</p><mark>{x.verdict}</mark></article>)}{decision.watch.map(x=><article key={x.name}><header><div><b>{x.name}</b><span>{x.role}</span></div></header><p>{x.note}</p><mark>{x.verdict}</mark></article>)}</div><div className="avoidColumn"><h3>× 不应用作硬规则</h3>{decision.avoid.map(x=><article key={x.name}><header><div><b>{x.name}</b></div>{x.metrics&&<strong>{x.metrics.win_rate.toFixed(1)}%<small>相关样本</small></strong>}</header>{x.metrics&&<div><span>样本 <b>{x.metrics.samples}</b></span><span>PF <b>{x.metrics.profit_factor.toFixed(2)}</b></span><span>期望 <b>{x.metrics.expectancy_pct>0?"+":""}{x.metrics.expectancy_pct.toFixed(2)}%</b></span></div>}<p>{x.note}</p><mark>{x.verdict}</mark></article>)}</div></div><footer>{decision.method_note}</footer></section>}
  <section className="overviewSectionHead"><div><small>02 · STOCK SELECTION</small><h2>{v2Current?"今日 V2 技术机会":"旧模型观察（等待今日更新）"}</h2><p>{v2Current?"新模型按技术因子入选，再由行业和大盘调整优先级。":"当前数据不是今天的新榜单，不作为今日推荐。"}</p></div><a href="/zh/watch/resonance/rare-opportunities">查看完整排行榜 →</a></section>
  <section className="opportunityWorkspace"><div className="opportunityList"><div className="opportunityLegend"><span>排名 / 标的</span><span>V2 优先级</span><span>主要入选理由</span><span>追踪状态</span></div><div className="opportunityRows">{opportunities.map((item,index)=>{const itemLinks=industry?.ticker_context[item.symbol]??[],itemCase=(casesByTicker[item.symbol]??[]).sort((a,b)=>b.first_seen_date.localeCompare(a.first_seen_date))[0];return <button type="button" key={item.symbol} className={activeSymbol===item.symbol?"selected":""} onClick={()=>setSelected(item.symbol)}><i>{String(index+1).padStart(2,"0")}</i><span><b>{item.symbol}</b><small>${item.price} · {item.level}</small></span><strong>{item.total_score||"—"}<small>{v2Current?"技术＋行业＋大盘":"旧观察分"}</small></strong><span className="opportunityEvidence">{item.components.slice(0,2).join(" · ")||"技术观察"}<small>{itemLinks.slice(0,1).map(x=>`${themes[x.theme_id]?.name??x.theme_id} · ${stateLabel[x.state]??x.state}`).join("")||"行业关系待确认"}</small></span><mark>{itemCase?itemCase.latest_current_status==="current"?"持续观察":itemCase.latest_current_status==="historical_recovered"?"历史恢复":"已入池":"新触发"}</mark></button>})}</div><footer>掉榜不删除：所有曾触发标的持续进入 Tracking Pool。</footer></div>
  <aside className="selectedResearch"><header><small>WHY IT RANKS HERE</small><h2>{chosen?.symbol??"—"} <span>{chosen?`$${chosen.price}`:""}</span></h2><p>{latestCase?`首次触发 ${latestCase.first_seen_date} · ${latestCase.lifecycle}`:"今天首次进入观察列表"}</p></header><section><div><b>旧生产分</b><strong>{chosen?.total_score??"—"}</strong></div><div><b>{registry?.factor_count??37} 因子观察</b><strong>{chosen?.experimental_observational_score??"—"}</strong></div><div><b>正式验证分</b><strong>{chosen?.official_score??"—"}</strong></div></section><dl><div><dt>技术</dt><dd>{evidence.map(x=>`${factors[x.factor_id]??x.factor_id}${x.hit?" · 当前":` · ${x.bars_since_hit}日前`}`).join("；")||chosen?.components.slice(0,4).join("；")||"暂无近期命中"}</dd><b data-tone={evidence.some(x=>x.hit)?"positive":"neutral"}>{evidence.some(x=>x.hit)?"有效":"观察"}</b></div><div><dt>行业</dt><dd>{classification?[classification.sector,classification.industry_group,classification.industry].filter(Boolean).join(" · "):links.map(x=>`${themes[x.theme_id]?.name??x.theme_id} · ${stateLabel[x.state]??x.state}`).join("；")||"暂无可靠分类"}</dd><b data-tone={links.some(x=>x.etf_context?.favorable_setup)?"positive":"neutral"}>{links.some(x=>x.etf_context?.favorable_setup)?"ETF支持":"未确认"}</b></div><div><dt>大盘</dt><dd>参考 {marketReference}：{reference?.above_ema50?"位于 EMA50 上方":"未站上 EMA50"}，20日 {pct(reference?.return_20d)}。</dd><b data-tone={reference?.above_ema50?"positive":"warning"}>{reference?.above_ema50?"支持":"谨慎"}</b></div><div><dt>追踪</dt><dd>{latestCase?`已观察 ${latestCase.forward.elapsed_sessions} 个交易日 · ${latestCase.forward.status}`:"触发后持续记录，不因掉榜删除。"}</dd><b data-tone="neutral">{cases.length} 个案例</b></div></dl><a href="/zh/watch/resonance/research?tab=forward">查看完整追踪 →</a></aside></section>
  <section className="overviewSectionHead compact"><div><small>03 · CONTEXT & RESEARCH</small><h2>热点与研究</h2><p>只放今天决策会用到的入口。</p></div></section>
  <section className="homeLowerGrid"><article className="themePulse"><small>行业热点</small><h2>{hotThemes.length?hotThemes.map(x=>x.name).join(" · "):"暂无明确领先行业"}</h2><p>根据行业 ETF 趋势、回撤位置与成交量观察，暂不改写技术分。</p><a href="/zh/watch/industry-radar">打开行业与大盘 →</a></article><article><small>永久追踪池</small><h2>{history?.cases.length??"—"} 个历史案例</h2><p>保存首次触发、每日变化、掉榜状态和后续收益。</p><a href="/zh/watch/resonance/research?tab=forward">查看历史追踪 →</a></article><article><small>因子研究 · v{registry?.registry_version??"0.8.0"}</small><h2>{registry?.factor_count??37} 个已登记因子</h2><p>已区分日线、完整周线和完整月线 EMA 支撑，并加入周/月看涨吞没与双吞没；先记录和回测，不改正式分。</p><a href="/zh/watch/resonance/research">进入研究中心 →</a></article></section>
  <details className={`overviewAudit ${synced?"isHealthy":"isBlocked"}`}><summary><span>{synced?"✓ 数据一致，未使用未来数据":"! 数据状态需要检查"}</span><small>Tracker {tracker.as_of} · Market {market?.as_of??"—"} · Industry {industry?.as_of??"—"}</small></summary><p>总览只在数据日期一致且 future_data_used=false 时合并跨系统结论。</p></details>
 </div>}</TrackerShell>
}
