"use client";
import { CSSProperties, ReactNode, useEffect, useState } from "react";

export type Direction="buy"|"sell"|"neutral";
export type Frame={macd:string;macd_score:number;macd_histogram:number;macd_histogram_change:number;energy:string;energy_streak:number;zero_zone:string;cross_zero_zone:string|null;bars_since_cross:number|null;rsi:string;rsi_score:number;rsi_value:number|null};
export type Item={symbol:string;price:number;macd_score:number;rsi_score:number;macd_resonance:number;rsi_resonance:number;chain_score:number;chain_reason:string;macd_gate_reason:string;combined_score:number;rsi_divergence_frames:string[];price_structure:{confirmed:boolean;score:number;label:string;evidence:string[]};ema_layer:{direction:Direction;label:string;ema20:number;ema50:number;fresh_cross:boolean};breakout_layer:{direction:Direction;label:string;level:number;distance:number};layer_directions:Record<string,Direction>;buy_layers:number;sell_layers:number;confluence_direction:"buy"|"sell"|"conflict"|"watch";confluence_label:string;volume:{label:string;score:number;ratio:number|null;near_bottom:boolean;direction:string};frames:Record<string,Frame>};
export type Report={as_of:string;universe:{cached:number;eligible:number};multi_confluence_top10:Item[];four_layer_bullish:Item[];four_layer_bearish:Item[];combined_top10:Item[];macd_top10:Item[];rsi_top10:Item[];volume_top10:Item[]};
export const periods=["日线","周线","月线"];
export const modules=[
 ["总览","/zh/watch/resonance"],["双指标确认","/zh/watch/resonance/confluence"],["MACD","/zh/watch/resonance/macd"],["RSI","/zh/watch/resonance/rsi"],["成交量","/zh/watch/resonance/volume"],
] as const;
export function useTracker(){const [data,setData]=useState<Report|null>(null);useEffect(()=>{fetch("/resonance-tracker.json").then(x=>x.json()).then(setData)},[]);return data}
export function TrackerShell({active,title,subtitle,children}:{active:string;title:string;subtitle:string;children:ReactNode}){
 const data=useTracker();
 return <main className="rtPage"><header className="rtSubHero"><div><a href="/zh/watch">← 盯盘助手</a><p>INDICATOR TRACKER</p><h1>{title}</h1><strong>{subtitle}</strong></div>{data&&<aside><small>数据截至</small><b>{data.as_of}</b><span>扫描 {data.universe.eligible} 只</span></aside>}</header><nav className="rtModuleNav">{modules.map(([label,url])=><a key={url} className={active===label?"active":""} href={url}>{label}</a>)}</nav>{!data&&active!=="需求取舍"?<div className="rtLoading">正在载入最新数据…</div>:children}</main>
}
function PeriodCell({frame,kind}:{frame:Frame;kind:"macd"|"rsi"}){const hot=kind==="macd"?frame.macd_score>=2:frame.rsi_score>=2;const value=kind==="macd"?frame.macd_histogram:(frame.rsi_value??50);const width=kind==="macd"?Math.min(100,18+Math.abs(value)*24):Math.max(0,Math.min(100,value));return <div className={`rtPeriod ${hot?"isHot":""}`}><small>{kind==="macd"?frame.zero_zone:`RSI ${frame.rsi_value??"—"}`}</small><b>{kind==="macd"?frame.macd:frame.rsi}</b><div className={`rtMiniTrack ${kind==="macd"?(value>=0?"positive":"negative"):value<=30?"oversold":"rsi"}`} aria-label={`${kind} 强度 ${width.toFixed(0)}%`}><i style={{width:`${width}%`}}/></div></div>}
function ScoreRing({score,kind,detail}:{score:number;kind:"macd"|"rsi";detail:string}){const max=kind==="macd"?55:12;const strength=Math.min(100,Math.round(score/max*100));return <div className="rtScore"><div className="rtScoreRing" style={{"--strength":`${strength}%`} as CSSProperties}><b>{score}</b></div><small>{detail}</small></div>}
export function SignalBoard({items,kind,combined}:{items:Item[];kind:"macd"|"rsi";combined:Set<string>}){return <div className="rtBoard"><div className="rtBoardHead"><span>标的</span>{periods.map(x=><span key={x}>{x}</span>)}<span>强度</span></div>{items.map((item,index)=><article className="rtSignalRow" key={item.symbol}><div className="rtTicker"><i>{String(index+1).padStart(2,"0")}</i><div><b>{item.symbol}</b><small>${item.price}</small></div>{combined.has(item.symbol)&&<mark>MACD ＋ RSI</mark>}{kind==="macd"&&<mark className={item.price_structure.confirmed?"structureOn":"structureOff"}>{item.price_structure.label}</mark>}</div>{periods.map(period=><PeriodCell key={period} frame={item.frames[period]} kind={kind}/>)}<ScoreRing score={kind==="macd"?item.macd_score:item.rsi_score} kind={kind} detail={kind==="macd"?`链条 +${item.chain_score}`:`${item.rsi_resonance}/3 周期`}/>{kind==="macd"&&<p className="rtReason">{item.chain_reason}<span>{item.price_structure.evidence.join(" · ")||"暂无价格结构确认"}</span></p>}</article>)}</div>}
const layerNames:Record<string,string>={macd:"MACD",rsi:"RSI",ema:"EMA",breakout:"突破"};
const directionText:Record<Direction,string>={buy:"看涨",sell:"看跌",neutral:"等待"};
export function ConfluenceMatrix({items}:{items:Item[]}){return <div className="rtMatrix"><div className="rtMatrixHead"><span>标的</span>{Object.keys(layerNames).map(x=><span key={x}>{layerNames[x]}</span>)}<span>结论</span></div>{items.map(item=><article key={item.symbol}><div className="rtMatrixTicker"><b>{item.symbol}</b><small>${item.price}</small></div>{Object.keys(layerNames).map(key=><div key={key} className={`rtLayerCell ${item.layer_directions[key]}`}><i/><b>{directionText[item.layer_directions[key]]}</b><small>{key==="macd"?`${item.frames["日线"].cross_zero_zone??item.frames["日线"].zero_zone} · 能量${item.frames["日线"].energy}${item.frames["日线"].energy_streak}根`:key==="rsi"?item.frames["日线"].rsi:key==="ema"?item.ema_layer.label:item.breakout_layer.label}</small></div>)}<div className={`rtMatrixVerdict ${item.confluence_direction}`}><b>{item.confluence_label}</b><small>{item.buy_layers}涨 / {item.sell_layers}跌</small></div></article>)}</div>}
