"use client";
import { CSSProperties, ReactNode, useEffect, useRef, useState } from "react";

export type Direction="buy"|"sell"|"neutral"|"conflict";
export type Frame={macd:string;macd_score:number;macd_line:number;signal_line:number;macd_histogram:number;macd_histogram_change:number;energy:string;energy_streak:number;zero_zone:string;cross_zero_zone:string|null;dead_cross_zero_zone:string|null;bars_since_cross:number|null;bars_since_dead_cross:number|null;rsi:string;rsi_score:number;rsi_value:number|null};
export type Item={symbol:string;price:number;macd_score:number;macd_rank_score:number;rsi_score:number;macd_resonance:number;rsi_resonance:number;chain_score:number;chain_reason:string;macd_gate_reason:string;combined_score:number;rsi_divergence_frames:string[];price_structure:{confirmed:boolean;score:number;label:string;evidence:string[]};ema_layer:{direction:Direction;score:number;stage:string;evidence:string[];label:string;ema20:number;ema50:number;fresh_cross:boolean};breakout_layer:{direction:Direction;score:number;stage:string;evidence:string[];label:string;level:number;distance:number};indicator_layers:Record<string,{direction:Direction;score:number;rank_score?:number;stage:string;evidence:string[]}>;layer_directions:Record<string,Direction>;buy_layers:number;sell_layers:number;confluence_direction:"buy"|"sell"|"conflict"|"watch";confluence_label:string;ranking_score:number;ranking_direction:Direction;ranking_breakdown:Record<string,number>;rank_reason:string;volume:{label:string;score:number;ratio:number|null;near_bottom:boolean;direction:string};frames:Record<string,Frame>};
type Candle={date:string;open:number;high:number;low:number;close:number;ema20:number;ema50:number;volume:number};
type Detail={chart:Candle[];audit:{latest_bar:string;history_rows:number;adjusted_prices:boolean;future_rows_used:boolean;latest_close:number}};
type RankingMethod={name:string;version:string;order:string[];score:string;warning:string};
export type Report={as_of:string;universe:{cached:number;eligible:number};ruleset:{version:string;timeframes:{direction:string[];timing:string};policy:string};consistency_audit:{ranking_digest:string;details_cover_all_published:boolean;duplicate_symbols:boolean;completed_higher_timeframes_only:boolean};details:Record<string,Detail>;ranking_method:RankingMethod;multi_confluence_top10:Item[];bullish_watch_top10:Item[];bearish_watch_top10:Item[];four_layer_bullish:Item[];four_layer_bearish:Item[];combined_top10:Item[];macd_top10:Item[];macd_buy_top10:Item[];macd_sell_top10:Item[];rsi_top10:Item[];volume_top10:Item[]};
type UpdateStatus={status:"up_to_date"|"stale"|"failed";source_latest_complete_date:string;tracker_as_of:string;radar_as_of:string;data_dates_match:boolean;last_successful_update_at:string};
export const periods=["日线","周线","月线"];
export const modules=[
 ["今日研究总览","/"],["指标共振","/zh/watch/resonance/macd"],["多因子","/zh/watch/resonance/rare-opportunities"],["行业雷达","/zh/watch/industry-radar"],["研究 / 实验","/zh/watch/resonance/research"],["市场环境","/zh/watch/market"],
] as const;
export function useTracker(){const [data,setData]=useState<Report|null>(null);useEffect(()=>{fetch("/resonance-tracker.json",{cache:"no-store"}).then(x=>x.json()).then(setData)},[]);return data}
function useUpdateStatus(){const [status,setStatus]=useState<UpdateStatus|null>(null);useEffect(()=>{fetch("/update-status.json",{cache:"no-store"}).then(x=>x.ok?x.json():null).then(setStatus).catch(()=>setStatus(null))},[]);return status}
export function TrackerShell({active,title,subtitle,children}:{active:string;title:string;subtitle:string;children:ReactNode}){
 const data=useTracker(),status=useUpdateStatus();const synced=!!data&&status?.status==="up_to_date"&&status.data_dates_match&&status.source_latest_complete_date===data.as_of;
 return <main className="rtPage"><header className="rtSubHero"><div><a href="/zh/watch/resonance/about">Sage Vista · 功能介绍</a><p>MACD RESEARCH WORKSPACE</p><h1>{title}</h1><strong>{subtitle}</strong></div>{data&&<aside className={synced?"isCurrent":"needsCheck"}><small>最新完整美股收盘</small><b>{data.as_of}</b><span className="rtSyncState">{synced?"✓ 已与数据源同步":"! 更新状态待核验"}</span><span>MACD / 雷达同日 · 扫描 {data.universe.eligible} 只</span>{status?.last_successful_update_at&&<time dateTime={status.last_successful_update_at}>成功更新 {new Date(status.last_successful_update_at).toLocaleString("zh-CN",{timeZone:"Australia/Melbourne",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false})}（墨尔本）</time>}</aside>}</header><nav className="rtModuleNav" aria-label="主要功能">{modules.map(([label,url])=><a key={url} className={active===label?"active":""} href={url}>{label}</a>)}</nav>{!data&&active!=="功能介绍"&&active!=="需求取舍"?<div className="rtLoading">正在载入最新数据…</div>:children}</main>
}
function PeriodCell({frame,kind}:{frame:Frame;kind:"macd"|"rsi"}){const hot=kind==="macd"?frame.macd_score>=2:frame.rsi_score>=2;const value=kind==="macd"?frame.macd_histogram:(frame.rsi_value??50);const width=kind==="macd"?Math.min(100,18+Math.abs(value)*24):Math.max(0,Math.min(100,value));return <div className={`rtPeriod ${hot?"isHot":""}`}><small>{kind==="macd"?frame.zero_zone:`RSI ${frame.rsi_value??"—"}`}</small><b>{kind==="macd"?frame.macd:frame.rsi}</b><div className={`rtMiniTrack ${kind==="macd"?(value>=0?"positive":"negative"):value<=30?"oversold":"rsi"}`} aria-label={`${kind} 强度 ${width.toFixed(0)}%`}><i style={{width:`${width}%`}}/></div></div>}
function ScoreRing({score,kind,detail}:{score:number;kind:"macd"|"rsi";detail:string}){const strength=Math.min(100,Math.round(score/25*100));return <div className="rtScore"><div className="rtScoreRing" style={{"--strength":`${strength}%`} as CSSProperties}><b>{score}</b></div><small>{detail}</small></div>}
export function SignalBoard({items,kind,combined}:{items:Item[];kind:"macd"|"rsi";combined:Set<string>}){const data=useTracker();const [selected,setSelected]=useState<Item|null>(null);return <><div className="rtBoard"><div className="rtBoardHead"><span>标的</span>{periods.map(x=><span key={x}>{x}</span>)}<span>强度</span></div>{items.map((item,index)=><article className="rtSignalRow" key={item.symbol}><button type="button" className="rtTicker" onClick={()=>setSelected(item)} aria-label={`查看${item.symbol}完整分析`}><i>{String(index+1).padStart(2,"0")}</i><div><b>{item.symbol}</b><small>${item.price} · 点击核验</small></div>{combined.has(item.symbol)&&<mark>MACD ＋ RSI</mark>}{kind==="macd"&&<mark className={item.price_structure.confirmed?"structureOn":"structureOff"}>{item.price_structure.label}</mark>}</button>{periods.map(period=><PeriodCell key={period} frame={item.frames[period]} kind={kind}/>)}<ScoreRing score={kind==="macd"?item.macd_score:item.rsi_score} kind={kind} detail={kind==="macd"?`规则 ${item.macd_rank_score}分`:`${item.rsi_resonance}/3 周期`}/>{kind==="macd"&&<p className="rtReason">{item.chain_reason}<span>{item.price_structure.evidence.join(" · ")||"暂无价格结构确认"}</span></p>}</article>)}</div>{selected&&data?.details[selected.symbol]&&<TickerDetail item={selected} detail={data.details[selected.symbol]} method={data.ranking_method} onClose={()=>setSelected(null)}/>}</>}
const layerNames:Record<string,string>={macd:"MACD",rsi:"RSI",ema:"EMA",breakout:"突破"};
const directionText:Record<Direction,string>={buy:"看涨",sell:"看跌",neutral:"等待",conflict:"反弹风险"};
function CandleChart({rows}:{rows:Candle[]}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas||!rows.length)return;const scale=window.devicePixelRatio||1;const width=canvas.clientWidth,height=canvas.clientHeight;canvas.width=width*scale;canvas.height=height*scale;const c=canvas.getContext("2d");if(!c)return;c.scale(scale,scale);c.clearRect(0,0,width,height);const pad={t:18,r:12,b:24,l:46};const highs=rows.map(x=>Math.max(x.high,x.ema20,x.ema50)),lows=rows.map(x=>Math.min(x.low,x.ema20,x.ema50));const max=Math.max(...highs),min=Math.min(...lows),range=max-min||1;const x=(i:number)=>pad.l+i*(width-pad.l-pad.r)/(rows.length-1);const y=(v:number)=>pad.t+(max-v)*(height-pad.t-pad.b)/range;c.strokeStyle="#e5ebe7";c.lineWidth=1;for(let i=0;i<4;i++){const yy=pad.t+i*(height-pad.t-pad.b)/3;c.beginPath();c.moveTo(pad.l,yy);c.lineTo(width-pad.r,yy);c.stroke();c.fillStyle="#849188";c.font="10px sans-serif";c.fillText((max-i*range/3).toFixed(1),4,yy+3)}const step=(width-pad.l-pad.r)/rows.length,body=Math.max(2,step*.55);rows.forEach((r,i)=>{const xx=x(i),up=r.close>=r.open;c.strokeStyle=up?"#23865b":"#c96055";c.fillStyle=c.strokeStyle;c.beginPath();c.moveTo(xx,y(r.high));c.lineTo(xx,y(r.low));c.stroke();c.fillRect(xx-body/2,Math.min(y(r.open),y(r.close)),body,Math.max(1,Math.abs(y(r.close)-y(r.open))))});([["#d69a36","ema20"],["#3979a8","ema50"]] as const).forEach(([color,key])=>{c.strokeStyle=color;c.lineWidth=1.5;c.beginPath();rows.forEach((r,i)=>i?c.lineTo(x(i),y(r[key])):c.moveTo(x(i),y(r[key])));c.stroke()});c.fillStyle="#7f8d85";c.font="10px sans-serif";c.fillText(rows[0].date,pad.l,height-6);c.fillText(rows.at(-1)?.date??"",width-72,height-6)},[rows]);return <canvas className="rtCandle" ref={ref} aria-label="最近60根日K线，含EMA20和EMA50"/>}
function TickerDetail({item,detail,method,onClose}:{item:Item;detail:Detail;method:RankingMethod;onClose:()=>void}){useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose()};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[onClose]);return <div className="rtDrawerBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside className="rtDrawer" role="dialog" aria-modal="true" aria-label={`${item.symbol}指标分析`}><header><div><small>可复核分析 · 数据截至 {detail.audit.latest_bar}</small><h2>{item.symbol} <span>${item.price}</span></h2><p>{item.confluence_label} · 规则匹配度 {item.ranking_score}/100</p></div><button onClick={onClose} aria-label="关闭分析">×</button></header><section className="rtChartPanel"><CandleChart rows={detail.chart}/><div className="rtChartLegend"><span className="candle">日K</span><span className="ema20">EMA20</span><span className="ema50">EMA50</span></div></section><section className="rtAuditFacts"><span><small>历史数据</small><b>{detail.audit.history_rows}根</b></span><span><small>复权价格</small><b>{detail.audit.adjusted_prices?"是":"否"}</b></span><span><small>未来数据</small><b>{detail.audit.future_rows_used?"异常":"未使用"}</b></span><span><small>收盘价校验</small><b>{detail.audit.latest_close}</b></span></section><section><h3>四层逐项验证</h3><div className="rtDetailLayers"><article><strong>MACD · {directionText[item.layer_directions.macd]}</strong>{periods.map(p=><p key={p}><b>{p}</b><span>{item.frames[p].macd} · {item.frames[p].cross_zero_zone??item.frames[p].zero_zone}<br/>MACD {item.frames[p].macd_line} / 信号 {item.frames[p].signal_line}<br/>能量{item.frames[p].energy}{item.frames[p].energy_streak}根，柱 {item.frames[p].macd_histogram}</span></p>)}</article><article><strong>RSI · {directionText[item.layer_directions.rsi]}</strong>{periods.map(p=><p key={p}><b>{p}</b><span>{item.frames[p].rsi} · RSI {item.frames[p].rsi_value??"—"}</span></p>)}</article><article><strong>EMA · {directionText[item.layer_directions.ema]}</strong><p><b>{item.ema_layer.label}</b><span>EMA20 {item.ema_layer.ema20}<br/>EMA50 {item.ema_layer.ema50}<br/>{item.ema_layer.fresh_cross?"最近5根出现交叉":"并非新近交叉"}</span></p></article><article><strong>价格突破 · {directionText[item.layer_directions.breakout]}</strong><p><b>{item.breakout_layer.label}</b><span>关键位 {item.breakout_layer.level}<br/>距离关键位 {(item.breakout_layer.distance*100).toFixed(2)}%</span></p></article></div></section><section><h3>排名为什么在这里</h3><div className="rtScoreBreakdown">{Object.entries(item.ranking_breakdown).map(([k,v])=><span key={k}><small>{k}</small><b className={v<0?"negative":""}>{v>0?`+${v}`:v}</b></span>)}</div><p className="rtMethod">排序依次使用：{method.order.join(" → ")}。{method.warning}</p></section></aside></div>}
export function ConfluenceMatrix({items,details,method}:{items:Item[];details:Record<string,Detail>;method:RankingMethod}){const [selected,setSelected]=useState<Item|null>(null);return <><div className="rtMatrix"><div className="rtMatrixHead"><span>排名 / 标的</span>{Object.keys(layerNames).map(x=><span key={x}>{layerNames[x]}</span>)}<span>结论</span></div>{items.map((item,index)=><button type="button" className="rtMatrixRow" key={item.symbol} onClick={()=>setSelected(item)}><div className="rtMatrixTicker"><em>{index+1}</em><b>{item.symbol}</b><small>${item.price} · {item.ranking_score}分</small></div>{Object.keys(layerNames).map(key=><div key={key} className={`rtLayerCell ${item.layer_directions[key]}`}><i/><b>{directionText[item.layer_directions[key]]} · {item.indicator_layers[key].score}/25</b><small>{item.indicator_layers[key].stage}</small></div>)}<div className={`rtMatrixVerdict ${item.confluence_direction}`}><b>{item.confluence_label}</b><small>{item.buy_layers}涨 / {item.sell_layers}跌 · 点击核验</small></div></button>)}</div>{selected&&details[selected.symbol]&&<TickerDetail item={selected} detail={details[selected.symbol]} method={method} onClose={()=>setSelected(null)}/>}</>}
