"use client";
import {TrackerShell} from "../tracker-ui";
import report from "../../../../../research/backtest/output/ranking-research-v1.json";
const pct=(x:number|null|undefined)=>x==null?"—":x.toFixed(2)+"%";
const periods:Record<string,string>={development:"2010–2024",validation_2025:"2025",forward_2026:"2026"};
export default function RankingResearch(){const random=report.methods.find(x=>x.method==="D")!;return <TrackerShell active="MACD研究" title="Ranking Research / 排名能力" subtitle="同一 point-in-time 候选池上的 MACD、Multi-Factor、Hybrid、Random 与 No-Ranking 对照。">
 <section className="btNotice"><b>结论：当前还不能证明任何 Ranking 具有可重复的排序 edge。</b><span>{report.benchmark.candidate_pool_signals} 个候选 · {report.benchmark.candidate_days} 个交易日</span></section>
 <section className="btAnswers"><article><small>真正有排序能力？</small><b>尚未证明</b><p>A/C 表面单调，但固定 Random 也单调，无法排除样本结构。</p></article><article><small>公平三档对照</small><b>只有5天</b><p>固定 benchmark 只有 {report.benchmark.days_with_10_plus} 天达到10个候选，远不足以下结论。</p></article><article><small>MACD 的角色</small><b>发现候选更合适</b><p>作为候选门槛已有独立 edge；决定精确顺序的证据仍弱。</p></article><article><small>Multi-Factor 排序</small><b>没有胜出</b><p>B 不满足 Top 1–3 &gt; 4–6 &gt; 7–10，也未明显打败 Random。</p></article></section>
 <section className="btPanel"><header><div><small>FIVE FIXED CONTROLS</small><h2>排名规则</h2></div><span>没有收益拟合或参数搜索</span></header><div className="rrRules">{Object.entries(report.rules).map(([k,v])=><article key={k}><small>{k}</small><b>{k==="A"?"MACD":k==="B"?"Multi-Factor":k==="C"?"Hybrid":k==="D"?"Random":"No Ranking"}</b><p>{v}</p></article>)}</div></section>
 <section className="btPanel"><header><div><small>ALL ELIGIBLE DAYS</small><h2>Rank Bucket 结果</h2></div><span>低排名只存在于候选拥挤日，需结合样本数阅读</span></header><div className="rrMethods">{report.methods.map(m=><article key={m.method}><header><span>{m.method}</span><b>{m.label}</b><mark>{m.monotonic_expectancy&&m.monotonic_profit_factor?"表面单调":"不单调"}</mark></header>{m.buckets.map(b=><p key={b.bucket}><strong>{b.bucket}</strong><span>n={b.overall.samples}</span><span>PF {b.overall.profit_factor??"—"}</span><span>Exp {pct(b.overall.expectancy_pct)}</span><span>Avg R {b.overall.average_r??"—"}</span><span>DD {pct(b.overall.max_drawdown_pct)}</span></p>)}</article>)}</div></section>
 <section className="btPanel"><header><div><small>COMMON ≥10-CANDIDATE DAYS</small><h2>真正可比的共同交易日</h2></div><span>仅5天，展示但不推断</span></header><div className="rrMethods">{report.common_10_candidate_days.map(m=><article key={m.method}><header><span>{m.method}</span><b>{m.label}</b></header>{m.buckets.map(b=><p key={b.bucket}><strong>{b.bucket}</strong><span>n={b.overall.samples}</span><span>PF {b.overall.profit_factor??"—"}</span><span>Exp {pct(b.overall.expectancy_pct)}</span></p>)}</article>)}</div></section>
 <section className="btPanel"><header><div><small>RANDOM & NO-RANK CONTROLS</small><h2>是否真正打败对照？</h2></div></header><div className="rrCompare"><article><small>No Ranking · 全候选</small><b>PF {report.no_ranking.overall.profit_factor}</b><strong>Expectancy {pct(report.no_ranking.overall.expectancy_pct)}</strong><span>n={report.no_ranking.overall.samples}</span></article><article><small>Random · Top 1–3</small><b>PF {random.buckets[0].overall.profit_factor}</b><strong>Expectancy {pct(random.buckets[0].overall.expectancy_pct)}</strong><span>n={random.buckets[0].overall.samples}</span></article>{report.methods.filter(x=>x.method!=="D").map(m=><article key={m.method}><small>{m.label} · Top 1–3</small><b>PF {m.buckets[0].overall.profit_factor}</b><strong>Expectancy {pct(m.buckets[0].overall.expectancy_pct)}</strong><span>相对 Random：PF {(Number(m.buckets[0].overall.profit_factor)-Number(random.buckets[0].overall.profit_factor)).toFixed(3)}</span></article>)}</div></section>
 <section className="btPanel"><header><div><small>PERIOD CONSISTENCY</small><h2>2010–2024 / 2025 / 2026</h2></div><span>各方法 Top 1–3</span></header><div className="rrPeriods">{report.methods.map(m=><article key={m.method}><b>{m.label}</b>{Object.entries(m.buckets[0].periods).map(([p,v])=><p key={p}><span>{periods[p]} · n={v.samples}</span><strong>PF {v.profit_factor??"—"} · Exp {pct(v.expectancy_pct)}</strong></p>)}</article>)}</div></section>
 <section className="btLimits"><b>研究判断</b><p>A/C 的全样本 Top 1–3 略高于 Random 与 No Ranking，但差距很小，且低排名样本被拥挤日严重混杂。B 没有单调性。第一版不支持修改 production Ranking；MACD 继续更适合候选发现，Multi-Factor 是否适合决定优先级仍需更宽候选池或更多独立样本。</p>{report.limitations.map(x=><span key={x}>{x}</span>)}</section>
 </TrackerShell>}
