"use client";
import {useEffect,useMemo,useState} from "react";
import {Item,TrackerShell,useTracker} from "../tracker-ui";
import {EmptyState,SectionHeader,StatusBadge} from "../product-ui";
type Factor={factor_id:string;available:boolean;hit:boolean;recent_hit:boolean;bars_since_hit:number|null;score_role:string};
type Snapshot={symbols:{symbol:string;factors:Factor[]}[]};
type Registry={factors:{id:string;name_zh:string;evidence_family:string}[]};
type Industry={themes:{theme_id:string;name:string;state:string}[];ticker_context:Record<string,{theme_id:string;state:string}[]>};
const json=(p:string)=>fetch(p,{cache:"no-store"}).then(x=>x.ok?x.json():null);
const stateName:Record<string,string>={Leadership:"领先","Pullback Watch":"回调观察",Recovery:"修复",Neutral:"中性",Unavailable:"数据不足"};
export default function Macd(){
 const data=useTracker(),[side,setSide]=useState<"buy"|"sell">("buy"),[selected,setSelected]=useState<string|null>(null),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[registry,setRegistry]=useState<Registry|null>(null),[industry,setIndustry]=useState<Industry|null>(null);
 useEffect(()=>{Promise.all([json("/daily-factor-snapshot.json"),json("/factor-registry.json"),json("/industry-radar.json")]).then(([s,r,i])=>{setSnapshot(s);setRegistry(r);setIndustry(i)})},[]);
 const source=data?(side==="buy"?data.macd_buy_top10:data.macd_sell_top10):[],chosen=source.find(x=>x.symbol===(selected??source[0]?.symbol));
 const names=useMemo(()=>Object.fromEntries((registry?.factors??[]).map(x=>[x.id,x.name_zh])),[registry]);
 const themeNames=useMemo(()=>Object.fromEntries((industry?.themes??[]).map(x=>[x.theme_id,x.name])),[industry]);
 const factors=(snapshot?.symbols.find(x=>x.symbol===chosen?.symbol)?.factors??[]).filter(x=>x.available&&(x.hit||x.recent_hit)).sort((a,b)=>(Number(b.hit)-Number(a.hit))||((a.bars_since_hit??99)-(b.bars_since_hit??99)));
 const themes=chosen?(industry?.ticker_context[chosen.symbol]??[]):[];
 return <TrackerShell active="指标共振" title="Technical Tracker" subtitle="按冻结的 Technical Tracker 顺序，快速判断哪些股票值得进一步研究。">{data&&<div className="trackerWorkspace">
  <section className="trackerToolbar"><div><button className={side==="buy"?"active":""} onClick={()=>{setSide("buy");setSelected(null)}}>看涨机会</button><button className={side==="sell"?"active":""} onClick={()=>{setSide("sell");setSelected(null)}}>看跌风险</button></div><p>排序来自现有 Tracker；Multi-Factor 与 Industry 只作为右侧解释。</p></section>
  <div className="trackerColumns"><section className="svPanel trackerList"><SectionHeader eyebrow="OPPORTUNITY SCREENER" title={side==="buy"?"看涨候选":"看跌候选"} description="点击一行查看完整研究上下文。"/><div className="trackerTable"><div className="trackerRow trackerHead"><span>Rank / Ticker</span><span>Technical Score</span><span>Setup</span><span>MACD</span><span>Pullback</span><span>Confirmed</span><span>Industry</span><span>Recent Evidence</span></div>{source.map((item,index)=><button key={item.symbol} className={`trackerRow ${chosen?.symbol===item.symbol?"selected":""}`} onClick={()=>setSelected(item.symbol)}><span><i>#{index+1}</i><b>{item.symbol}</b></span><strong>{item.macd_rank_score}</strong><span>{item.confluence_label}</span><span>{item.frames["日线"].macd}</span><span>{item.price_structure.label}</span><span>{item.price_structure.confirmed?"是":"待确认"}</span><span>{(industry?.ticker_context[item.symbol]??[]).slice(0,1).map(x=>stateName[x.state]).join()||"—"}</span><span>{(snapshot?.symbols.find(x=>x.symbol===item.symbol)?.factors??[]).filter(x=>x.available&&(x.hit||x.recent_hit)).slice(0,2).map(x=>names[x.factor_id]??x.factor_id).join(" · ")||"—"}</span></button>)}</div></section>
   <aside className="svPanel trackerDetail">{chosen?<><header><small>SELECTED STOCK</small><h2>{chosen.symbol} <span>${chosen.price}</span></h2><StatusBadge state={chosen.confluence_direction}>{chosen.confluence_label}</StatusBadge></header><section><h3>Technical Summary</h3><div className="trackerScore"><strong>{chosen.macd_rank_score}</strong><span>Technical Score<br/>{chosen.rank_reason}</span></div></section><section><h3>Multi-Factor Evidence</h3>{factors.length?<ul>{factors.slice(0,8).map(f=><li key={f.factor_id}><b>{names[f.factor_id]??f.factor_id}</b><span>{f.hit?"当前":"近期"}{f.bars_since_hit?` · ${f.bars_since_hit} sessions ago`:""} · {f.score_role}</span></li>)}</ul>:<p>暂无当前或近期证据。</p>}<a href={`/zh/watch/resonance/rare-opportunities?symbol=${chosen.symbol}`}>打开 27-factor 分析 →</a></section><section><h3>Industry Context</h3>{themes.length?themes.map(t=><p key={t.theme_id}><b>{themeNames[t.theme_id]??t.theme_id}</b> <StatusBadge state={t.state}>{stateName[t.state]??t.state}</StatusBadge></p>):<p>暂无已确认 Theme membership。</p>}</section><section><h3>Risks</h3><p>{chosen.sell_layers?`${chosen.sell_layers} 个技术层偏弱或冲突。`:"当前未见反向层确认；仍需人工核验价格结构。"}</p></section><section><h3>Signal History</h3><a href="/zh/watch/resonance/research?tab=forward">前往 Forward Testing 查看 →</a></section></>:<EmptyState title="当前榜单没有候选"/>}</aside>
  </div>
 </div>}</TrackerShell>
}
