"use client";
import {TrackerShell} from "../tracker-ui";
import report from "../../../../../research/backtest/output/selection-research-v1.json";

type Metrics={samples:number;win_rate:number|null;profit_factor:number|null;expectancy_pct:number|null;average_r:number|null;stop_out_rate:number|null;max_drawdown_pct:number|null;average_holding_bars:number|null};
const pct=(x:number|null)=>x==null?"—":`${x.toFixed(2)}%`;
const num=(x:number|null)=>x==null?"—":x.toFixed(3);
const periods=[['development','2010–2024'],['validation_2025','2025'],['forward_2026','2026']] as const;
function MetricsCard({title,m,warning}:{title:string;m:Metrics;warning?:string}){return <article><header><b>{title}</b>{warning&&<mark>{warning}</mark>}</header><strong>PF {num(m.profit_factor)}</strong><span>Expectancy {pct(m.expectancy_pct)}</span><p>n={m.samples} · 胜率 {pct(m.win_rate)} · Avg R {num(m.average_r)}</p><small>止损 {pct(m.stop_out_rate)} · 持有 {m.average_holding_bars?.toFixed(1)??'—'} bars · DD {pct(m.max_drawdown_pct)}</small></article>}
export default function SelectionResearch(){const leadership=report.leadership,strong=report.strong_trend_pullback;return <TrackerShell active="MACD研究" title="Stock Selection / 选股研究" subtitle="Leadership 与 Strong-Trend Pullback 是两个独立 hypothesis，不合并评分，也不改变 production。">
 <section className="btNotice"><b>结论：Leadership 没有超过基准；Pullback 数字亮眼，但跨时期与样本量都未通过验证。</b><span>固定执行：Confirmed + Long-Term Trend + Next-Day Open + Support −5% + 2R</span></section>
 <section className="btAnswers"><article><small>Leadership</small><b>没有证明</b><p>PF {leadership.overall.profit_factor}、Expectancy {pct(leadership.overall.expectancy_pct)}，均低于固定基准。</p></article><article><small>Strong-Trend Pullback</small><b>有信号，未验证</b><p>整体 PF {strong.overall.profit_factor}，但仅 {strong.overall.samples} 个样本；2025 的4个样本全部止损。</p></article><article><small>跨时期稳定性</small><b>两者都不稳定</b><p>Leadership 2025转负；Pullback 在开发、2025和2026方向剧烈变化。</p></article><article><small>两组重叠</small><b>{report.overlap.samples} 个</b><p>V1 条件刻意区分近期强势与短期明显回调，因此没有重叠。</p></article></section>
 <section className="btPanel"><header><div><small>FIXED HYPOTHESES</small><h2>两种选股逻辑</h2></div><span>阈值预先固定 · 没有收益优化</span></header><div className="srHypotheses"><article><small>A · LEADERSHIP</small><h3>强势领涨</h3><p>长期强、近期也强，并用成交量确认资金参与。</p><ul>{report.rules.leadership.map(x=><li key={x}>{x}</li>)}</ul></article><article><small>B · STRONG-TREND PULLBACK</small><h3>强趋势回调</h3><p>长期相对强度仍在，但短期明显卖出并回到当时已知支撑附近。</p><ul>{report.rules.pullback.map(x=><li key={x}>{x}</li>)}</ul></article></div><p className="srIndustry"><b>Industry RS：</b>{report.rules.industry_relative_strength}。V1 明确缺省，不用今天的行业标签回填历史。</p></section>
 <section className="btPanel"><header><div><small>OVERALL CONFIRMED</small><h2>与固定 Long benchmark 对比</h2></div></header><div className="srMetrics"><MetricsCard title="Current Benchmark" m={report.benchmark.metrics}/><MetricsCard title="Leadership" m={leadership.overall} warning="未验证"/><MetricsCard title="Strong-Trend Pullback" m={strong.overall} warning="样本不足"/></div></section>
 <section className="btPanel"><header><div><small>PERIOD CONSISTENCY</small><h2>开发期 / 独立验证期 / 前向期</h2></div><span>不能用整体均值掩盖失败时期</span></header><div className="srPeriods"><div><h3>Leadership</h3>{periods.map(([k,label])=><MetricsCard key={k} title={label} m={leadership.periods[k]}/>)}</div><div><h3>Strong-Trend Pullback</h3>{periods.map(([k,label])=><MetricsCard key={k} title={label} m={strong.periods[k]} warning={k==='validation_2025'?'验证失败':undefined}/>)}</div></div></section>
 <section className="btPanel"><header><div><small>DIAGNOSTICS</small><h2>Pullback 是二次启动，还是 falling knife？</h2></div></header><div className="srDiagnostics"><article><small>平均60D回撤</small><b>{pct(strong.diagnostics.average_drawdown_60d_pct)}</b><p>确实筛到了明显短期卖出。</p></article><article><small>126D相对SPY</small><b>+{pct(strong.diagnostics.average_rs_126_spy_pct)}</b><p>长期相对强度仍然明显为正。</p></article><article><small>卖出量衰减</small><b>{pct(strong.diagnostics.selling_volume_decay_pct)}</b><p>这是状态记录，不是入选门槛。</p></article><article><small>Early Watch Pullback</small><b>PF {report.early_watch.strong_trend_pullback.profit_factor}</b><p>止损率 {pct(report.early_watch.strong_trend_pullback.stop_out_rate)}，未确认时更像 falling knife。</p></article></div><p className="btMethod">Confirmed 样本在定义上保持长期趋势和相对强度，整体不像普通下降趋势；但2025验证失败说明这层保护尚不足以证明可重复 edge。</p></section>
 <section className="btPanel"><header><div><small>MARKET CONTEXT CONTROL</small><h2>Leadership 是否只是跟随大盘上涨？</h2></div></header><div className="srMetrics"><MetricsCard title="SPY 长期趋势向上" m={report.leadership_market_context.spy_long_trend}/><MetricsCard title="SPY 非长期趋势" m={report.leadership_market_context.spy_not_long_trend}/></div><p className="btMethod">Leadership 在 SPY 长期趋势向上时仍只有 PF {report.leadership_market_context.spy_long_trend.profit_factor}，因此它的弱结果不能解释成“优势只是牛市带来的”；V1 反而没有观察到优势。</p></section>
 <section className="btLimits"><b>研究边界与审计</b><p>选股特征只读取信号日及之前的数据；入场、Stop、TP 和原始历史信号全部沿用冻结 benchmark。没有调整生产扫描、Ranking、因子权重、Discord 或自动任务。</p>{report.limitations.map(x=><span key={x}>{x}</span>)}</section>
 </TrackerShell>}
