"use client";
import {useEffect,useMemo,useState} from "react";
type Audit={status:string;provider:string;universe:{primary_exchange_common_active:number;primary_exchange_common_delisted:number;symbol_collisions:number};history_checks:{symbol:string;rows:number;first:string;last:string;missing_adjusted_close:number;duplicate_dates:number}[];corporate_actions:Record<string,number>;limitations:string[]};
type Metric={factor:string;horizon:number;mean_ic:number|null;ic_positive_pct:number|null;observations:number;spread:number|null};
type Pilot={status:string;sample:{requested_active:number;requested_delisted:number;loaded:number;eligible_active:number;eligible_delisted:number;stock_months:number;dates:number;start:string;end:string};metrics:Metric[];decision:string;limitations:string[]};
type Combo={combination:string;horizon:number;dates:number;observations:number;mean_ic:number|null;ic_positive_pct:number|null;spread:number|null};
type Validation={status:string;sample:{loaded:number;eligible_active:number;eligible_delisted:number;stock_months:number;dates:number;start:string;end:string};execution:{entry:string;time_stop:string};combinations:Record<string,Combo[]>;decision:string;limitations:string[]};
const names:Record<string,string>={volatility_contraction:"Volatility contraction",breakout_252:"52-week breakout",low_volatility:"Low volatility",liquidity:"Liquidity",rsi_14:"RSI (14)",momentum_12_1:"12–1 momentum",volume_expansion:"Volume expansion",trend_quality:"Trend quality",relative_strength_6m:"Relative strength"};
export default function DataQuality(){const [audit,setAudit]=useState<Audit|null>(null),[pilot,setPilot]=useState<Pilot|null>(null),[validation,setValidation]=useState<Validation|null>(null);useEffect(()=>{Promise.all([fetch("/data-audit.json").then(x=>x.json()),fetch("/eodhd-factor-pilot.json").then(x=>x.json()),fetch("/eodhd-factor-validation.json").then(x=>x.json())]).then(([a,p,v])=>{setAudit(a);setPilot(p);setValidation(v)})},[]);const top=useMemo(()=>pilot?.metrics.filter(x=>x.horizon===60).sort((a,b)=>(b.mean_ic??-9)-(a.mean_ic??-9)).slice(0,6)??[],[pilot]);if(!audit||!pilot||!validation)return <main className="datalab">Loading provider audit…</main>;const forward=validation.combinations.forward_test;return <main className="datalab"><header><p className="label">NORTHSTAR / DATA QUALITY</p><h1>Trust the history before the result.</h1><span>EODHD is now the candidate source for survivorship-aware price research.</span></header><section className="datastats"><div><small>HISTORIES LOADED</small><b>{validation.sample.loaded.toLocaleString()}</b><span>active and delisted sample</span></div><div><small>EVER ELIGIBLE</small><b>{validation.sample.eligible_active+validation.sample.eligible_delisted}</b><span>{validation.sample.eligible_active} active + {validation.sample.eligible_delisted} delisted</span></div><div><small>STOCK-MONTHS</small><b>{validation.sample.stock_months.toLocaleString()}</b><span>{validation.sample.start} → {validation.sample.end}</span></div><div><small>TESTED FACTORS</small><b>13 + 3</b><span>individual factors + combinations</span></div></section><section className="datagrid"><article><p className="label">HISTORY AUDIT</p><h2>{audit.status.replaceAll("_"," ")}</h2>{audit.history_checks.map(x=><div className="historycheck" key={x.symbol}><b>{x.symbol}</b><span>{x.first} → {x.last}</span><small>{x.rows.toLocaleString()} bars · {x.duplicate_dates} duplicate dates</small></div>)}</article><article><p className="label">2026 FORWARD MONITOR · 10 DAYS</p><h2>Combination behavior</h2><div className="pilothead"><span>Combination</span><span>IC</span><span>Spread</span></div>{forward.map(x=><div className="pilotrow" key={x.combination}><b>{x.combination.replaceAll("_"," ")}</b><span>{x.mean_ic?.toFixed(3)}</span><span>{x.spread===null?"—":`${(x.spread*100).toFixed(2)}%`}</span></div>)}<mark>Only {forward[0]?.dates??0} monthly dates are available in 2026. This is monitoring evidence, not promotion evidence.</mark></article></section><section className="datagrid"><article><p className="label">EXECUTION REALISM</p><h2>Signal close → next open</h2><p>{validation.execution.entry}. {validation.execution.time_stop}.</p></article><article><p className="label">DECISION</p><h2>Research only</h2><p>{validation.decision}</p></article></section><section className="datalimits"><p className="label">WHAT STILL BLOCKS PROMOTION</p>{validation.limitations.map(x=><span key={x}>{x}</span>)}</section></main>}
