"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {TrackerShell} from "../tracker-ui";

type Metric={side:string;regime:string;regime_label:string;factor:string;horizon:number;samples:number;win_rate:number|null;trimmed_mean_return:number|null;median_return:number|null;mean_adverse:number|null;spy_excess_return:number|null;qqq_excess_return:number|null;beat_spy_rate:number|null;beat_qqq_rate:number|null};
type Candidate={side:string;factor:string;horizon:number;status:string;development:Metric;validation:Metric;forward:Metric};
type Incremental={factor:string;verdict:string;stages:Record<"development"|"validation"|"forward",Metric>;deltas:Record<"development"|"validation"|"forward",{win_rate:number;trimmed_mean_return:number;sample_retention:number}>};
type MonthlyTest={factor:string;label:string;regime:string;horizons:{horizon:number;stages:Record<"development"|"validation"|"forward",Metric>}[]};
type PatternTest={factor:string;label:string;holding_days:number;verdict:string;stages:Record<"development"|"validation"|"forward",Metric>;deltas:Record<"development"|"validation"|"forward",{win_rate:number|null;trimmed_mean_return:number|null;sample_retention:number}>};
type HigherTimeframeTest={trigger:"周线"|"月线";factors:string[];horizons:{horizon:number;stages:Record<"development"|"validation"|"forward",Record<string,Metric>>}[]};
type MultiLevel={minimum_score:number;verdict:string;stages:Record<"development"|"validation"|"forward",Metric>;deltas:Record<"development"|"validation"|"forward",{win_rate:number|null;trimmed_mean_return:number|null}>};
type MultiFactorTest={core:string;components:string[];horizons:{horizon:number;levels:MultiLevel[]}[];contributions:{component:string;horizons:{horizon:number;stages:Record<"development"|"validation"|"forward",Metric>;deltas:Record<"development"|"validation"|"forward",{win_rate:number|null;trimmed_mean_return:number|null}>}[]}[];score_rule:string};
type Study={universe:{eligible:number;events:number;trigger_counts:Record<string,number>;listing_status_histories:Record<string,number>;listing_status_events:Record<string,number>;history_earliest:string;history_latest:string;median_daily_bars:number};pattern_trend_gate:{plain:string;rule:string};splits:{development:Metric[];validation:Metric[];forward:Metric[]};validated_combinations:Candidate[];incremental_tests:Incremental[];monthly_horizon_tests:MonthlyTest[];higher_timeframe_support_tests:HigherTimeframeTest[];pattern_incremental_tests:PatternTest[];multifactor_tests:MultiFactorTest;execution:string;lookahead:string;warning:string};
const baseFactors=["日线零轴下金叉","周线零轴下金叉","月线零轴下金叉"];
const untestedFactors=["未补跳空缺口＋价格确认＋日线MACD金叉","锤头线＋日线MACD金叉","底部放量＋日线MACD金叉","突破后回踩＋日线MACD金叉"];
const stageMeta={development:{label:"2024年前",color:"#75847c"},validation:{label:"2025验证",color:"#d59b3e"},forward:{label:"2026观察",color:"#19875a"}} as const;
function WinRateChart({test}:{test:MonthlyTest}){
 const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const draw=()=>{const box=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1,w=box.width,h=box.height;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext("2d");if(!c)return;c.scale(dpr,dpr);c.clearRect(0,0,w,h);const stages=Object.keys(stageMeta) as (keyof typeof stageMeta)[],vals=test.horizons.flatMap(x=>stages.map(s=>x.stages[s].win_rate).filter((v):v is number=>v!==null)),low=Math.floor((Math.min(...vals)-5)/5)*5,high=Math.ceil((Math.max(...vals)+5)/5)*5,range=Math.max(10,high-low),pad={l:38,r:18,t:18,b:34};c.font="11px system-ui";c.fillStyle="#7b8981";c.strokeStyle="#e3e9e5";c.lineWidth=1;[0,.5,1].forEach(t=>{const y=pad.t+t*(h-pad.t-pad.b);c.beginPath();c.moveTo(pad.l,y);c.lineTo(w-pad.r,y);c.stroke();c.fillText(`${Math.round(high-t*range)}%`,2,y+4)});const xAt=(i:number)=>pad.l+i/(test.horizons.length-1)*(w-pad.l-pad.r),yAt=(v:number)=>pad.t+(high-v)/range*(h-pad.t-pad.b);stages.forEach(stage=>{const pts=test.horizons.map((x,i)=>({x:xAt(i),y:yAt(x.stages[stage].win_rate??low)}));c.beginPath();c.moveTo(pts[0].x,pts[0].y);for(let i=0;i<pts.length-1;i++){const p0=pts[Math.max(0,i-1)],p1=pts[i],p2=pts[i+1],p3=pts[Math.min(pts.length-1,i+2)];c.bezierCurveTo(p1.x+(p2.x-p0.x)/6,p1.y+(p2.y-p0.y)/6,p2.x-(p3.x-p1.x)/6,p2.y-(p3.y-p1.y)/6,p2.x,p2.y)}c.strokeStyle=stageMeta[stage].color;c.lineWidth=3;c.lineCap="round";c.stroke();pts.forEach(p=>{c.beginPath();c.arc(p.x,p.y,4,0,Math.PI*2);c.fillStyle=stageMeta[stage].color;c.fill();c.strokeStyle="#fff";c.lineWidth=2;c.stroke()})});test.horizons.forEach((x,i)=>{c.fillStyle="#718078";c.textAlign="center";c.fillText(`${x.horizon}日`,xAt(i),h-8)});c.textAlign="start"};draw();const ro=new ResizeObserver(draw);ro.observe(canvas);return()=>ro.disconnect()},[test]);return <div className="rtLineChart" role="img" aria-label={`${test.label}不同持有期胜率平滑曲线图`}><canvas ref={ref}/><div className="rtChartLegend">{(Object.keys(stageMeta) as (keyof typeof stageMeta)[]).map(s=><span key={s}><i style={{background:stageMeta[s].color}}/>{stageMeta[s].label}</span>)}</div></div>
}

export default function Research(){
 const [data,setData]=useState<Study|null>(null);useEffect(()=>{fetch("/macd-factor-backtest.json").then(x=>x.json()).then(setData)},[]);
 const baselines=useMemo(()=>data?baseFactors.map(f=>[5,10,20].map(h=>{const find=(split:keyof Study["splits"])=>data.splits[split].find(x=>x.side==="buy"&&x.regime==="all"&&x.factor===f&&x.horizon===h)!;const development=find("development"),validation=find("validation"),forward=find("forward");return {factor:f,horizon:h,development,validation,forward,average:((development.win_rate??0)+(validation.win_rate??0)+(forward.win_rate??0))/3}}).sort((a,b)=>b.average-a.average)[0]):[],[data]);
 const stable=useMemo(()=>data?data.validated_combinations.filter(x=>x.side==="buy"&&x.development.samples>=1000&&x.validation.samples>=100&&x.forward.samples>=100).sort((a,b)=>Math.min(b.development.win_rate??0,b.validation.win_rate??0,b.forward.win_rate??0)-Math.min(a.development.win_rate??0,a.validation.win_rate??0,a.forward.win_rate??0)).slice(0,5):[],[data]);
 const monthlyCross=data?.monthly_horizon_tests.find(x=>x.factor==="月线零轴下金叉");
 const monthly100=monthlyCross?.horizons.find(x=>x.horizon===100);
 const currentPatterns=data?.pattern_incremental_tests.filter(x=>x.label==="底部Doji"||x.label==="底部Bullish Engulfing")??[];
 const archivedPatterns=data?.pattern_incremental_tests.filter(x=>x.label!=="底部Doji"&&x.label!=="底部Bullish Engulfing"&&x.label!=="K线聚集区"&&x.label!=="Volume Profile筹码峰"&&x.label!=="完整筹码密集峰"&&x.label!=="Fibonacci 0.5支撑")??[];
 const experimentOne=useMemo(()=>data?[20,100].map(horizon=>({horizon,stages:Object.fromEntries((Object.keys(stageMeta) as (keyof typeof stageMeta)[]).map(split=>[split,data.splits[split].find(x=>x.side==="buy"&&x.regime==="all"&&x.factor==="长期趋势合格＋日线金叉"&&x.horizon===horizon)!])) as Record<keyof typeof stageMeta,Metric>})):[],[data]);
 const experimentTwo=data?.pattern_incremental_tests.find(x=>x.label==="K线聚集区");
 const experimentThree=data?.pattern_incremental_tests.find(x=>x.label==="Volume Profile筹码峰");
 const experimentFour=data?.pattern_incremental_tests.find(x=>x.label==="完整筹码密集峰");
 const experimentFive=data?.pattern_incremental_tests.find(x=>x.label==="Fibonacci 0.5支撑");
 const multifactor=data?.multifactor_tests;
 const multi20=multifactor?.horizons.find(x=>x.horizon===20);
 const gap20=multifactor?.contributions.find(x=>x.component==="上方未补跳空缺口")?.horizons.find(x=>x.horizon===20);
 const weeklyLarge=data?.higher_timeframe_support_tests.find(x=>x.trigger==="周线");
 const monthlyLarge=data?.higher_timeframe_support_tests.find(x=>x.trigger==="月线");
 const largeAt=(test:HigherTimeframeTest|undefined,horizon:number,factor:number,stage:keyof typeof stageMeta)=>test?.horizons.find(x=>x.horizon===horizon)?.stages[stage][test.factors[factor]];
 return <TrackerShell active="MACD研究" title="MACD 因子研究" subtitle="研究样本、周期结论和策略表现与当前个股排行榜完全分开。">
  {data&&<>
   <section className="researchDashboard"><header><div><small>RESEARCH DASHBOARD</small><h2>研究模块</h2><p>每项研究独立验证一个问题，失败结果也永久保留。</p></div><aside><small>CURRENT BENCHMARK</small><b>Confirmed + Long-Term Trend + Support −5% + 2R</b><strong>PF 1.178 <i/> Expectancy +0.801%</strong><span>Research benchmark · 不是 production trading recommendation</span></aside></header><div>{[
    ["Signal Validation","Tracker Backtest","V1","验证 Tracker 历史信号、排名和长期趋势","/zh/watch/resonance/strategy-backtest","已完成"],
    ["Risk Management","Stop Loss / Risk-Reward","V2","比较固定 Stop 与 TP 的风险收益结构","/zh/watch/resonance/strategy-backtest-v2","已完成"],
    ["Market Context","Market Regime","V1","检验趋势、动能与 Breadth 是否改善 Long","/zh/watch/resonance/market-regime","未验证"],
    ["Factor Research","Factor Attribution","V1","解释单因子贡献与 Rank / Score 分歧","/zh/watch/resonance/factor-attribution","已完成"],
    ["Ranking Ability","Ranking Research","V1","比较 MACD、多因子、Hybrid 与随机对照","/zh/watch/resonance/ranking-research","未验证"],
    ["Stock Selection","Leadership vs Pullback","V1","比较强势领涨与强趋势回调后的二次启动","/zh/watch/resonance/selection-research","未验证"],
   ].map(x=><article key={x[1]}><header><span>{x[0]}</span><small>{x[2]}</small></header><h3>{x[1]}</h3><p>{x[3]}</p><footer><mark>{x[5]}</mark><a href={x[4]}>进入研究 →</a></footer></article>)}</div></section>
   <section className="rtSummary"><article className="rtSummaryPrimary"><small>一句话结论</small><b>20日暂无加分项</b><p>目前测过的形态都没有稳定提高日线MACD金叉后的20日胜率</p></article><article><small>历史范围</small><b>2000—2026</b><p>{data.universe.history_earliest} 至 {data.universe.history_latest}</p></article><article><small>合格股票</small><b>{data.universe.eligible.toLocaleString()}</b><p>长期上涨或横盘才进入形态测试</p></article><article><small>MACD事件</small><b>{data.universe.events.toLocaleString()}</b><p>日、周、月完整收盘后确认</p></article></section>
   <section className="rtAnswerGrid"><article className="answerNo"><small>20日组合</small><h2>没有一个稳定成立</h2><p>双底、三推、RSI底背离、底部Doji和看涨吞没，目前都不能提高tracker权重。</p></article><article className="answerUse"><small>仍值得保留</small><h2>日线MACD看时机</h2><p>单独MACD金叉仍作为观察信号；月线金叉只用于中期60—100日研究，不和20日结论混在一起。</p></article><article><small>实际怎么做</small><h2>失败结果继续记录</h2><p>以后新增因子都和同一个MACD基准比较；不稳定或失败就留档，不包装成可用信号。</p></article></section>
   {multi20&&gap20&&<section className="rtMultiSummary"><header><div><small>多因子评分实验 · 已完成</small><h2>条件越多，并没有让MACD胜率稳定变高</h2></div><mark>暂不启用总分</mark></header><div><article><small>0分基础</small><b>53%—56%</b><p>长期趋势合格、已回调至少5%、日线MACD金叉。</p></article><article><small>至少4项确认</small><b>52%—58%</b><p>2025只有51.6%，2026为54.3%，没有形成逐级提高。</p></article><article className="watch"><small>唯一值得单独再查</small><b>上方未补缺口</b><p>三段胜率都提高，但收益没有三段同步改善，暂时只列候选。</p></article></div><footer>人话结论：把六个指标等权相加会把有效和无效条件混在一起；5—6分的高胜率来自极少样本，不能使用。</footer></section>}
   {weeklyLarge&&monthlyLarge&&<section className="rtHigherSummary"><header><div><small>大周期实验 · 周线与月线</small><h2>看3—6个月，月线金叉比周线更值得继续研究</h2></div><mark>聚集区没有加分</mark></header><div><article><small>周线金叉 · 6个月</small><b>约56%—61%</b><p>三段胜率59.6% / 60.9% / 56.2%。能上涨，但没有稳定跑赢市场。</p></article><article className="best"><small>月线金叉 · 6个月</small><b>约65%—70%</b><p>三段胜率64.5% / 68.1% / 70.3%。时间拉长后明显更一致。</p></article><article><small>加上K线聚集区</small><b>不采用</b><p>周线没有稳定改善；月线验证期明显变差，近期完整样本也太少。</p></article></div><footer>人话结论：月线金叉适合当作“未来半年值得持续观察”的慢信号；K线聚集区不能让它更可靠。</footer></section>}
   <section className="rtPatternResults"><header><div><small>这次测试 · 2000—2026</small><h2>底部K线配合MACD金叉，能不能提高20日胜率？</h2></div><span>统一持有20个交易日</span></header><p className="rtPatternGate">共同前提：{data.pattern_trend_gate.plain}。Doji或看涨吞没必须出现在金叉当天或此前4天，并位于过去60日价格区间的下方30%。</p><div>{currentPatterns.map(test=><article key={test.factor} className={`pattern${test.verdict}`}><mark>{test.verdict}</mark><h3>{test.label}</h3><p><b>2000—2024</b>：{test.stages.development.win_rate??"—"}% · {test.stages.development.samples.toLocaleString()}次</p><p><b>2025</b>：{test.stages.validation.win_rate??"—"}% · 比MACD <strong>{(test.deltas.validation.win_rate??0)>0?"+":""}{test.deltas.validation.win_rate??"—"}个百分点</strong></p><small>2026：{test.stages.forward.samples}次 · 胜率 {test.stages.forward.win_rate??"—"}%</small></article>)}</div></section>
   <section className="rtStudyArchive"><header><div><small>已经测过 · 永久记录</small><h2>这些条件目前不能给MACD加分</h2></div><span>失败结果也保留</span></header><div>{archivedPatterns.map(test=><article key={test.factor}><mark>{test.verdict}</mark><h3>{test.label}</h3><p>{test.verdict==="不成立"?"长期结果没有稳定改善。":"不同时间段方向不一致，暂时不能使用。"}</p><small>2000—2024：{test.stages.development.win_rate??"—"}%　·　2025：{test.stages.validation.win_rate??"—"}%　·　2026：{test.stages.forward.win_rate??"—"}%</small></article>)}</div><p>共同前提：长期上涨或横盘；下一日开盘进入；持有20个交易日。已确认退市股票 {data.universe.listing_status_histories.delisted??0} 只，身份尚未匹配 {data.universe.listing_status_histories.unknown??0} 只。</p></section>
   <section className="rtPlainResearch"><div><small>看到信号后的简单顺序</small><h2>先看日线，再看月线，最后决定拿多久</h2><p>页面会继续把日线、周线、月线分别展示，但不会把它们揉成一个看似精确的总分。这样你能知道，到底是哪一层信号在起作用。</p></div><div className="rtPlainSteps"><article><i>1</i><b>日线刚金叉</b><span>加入观察，不代表立刻买</span></article><article><i>2</i><b>月线也刚金叉</b><span>允许观察更长时间</span></article><article><i>3</i><b>周月只是已多头</b><span>暂不额外加分</span></article></div></section>
   {monthlyCross&&<section className="rtHeroCurve"><header><div><small>最值得继续观察的结果</small><h2>月线刚金叉后，短看20日不够，60—100日更符合它的节奏</h2></div><strong>观察结论，不是买入指令</strong></header><WinRateChart test={monthlyCross}/><div className="rtHumanNumbers"><span><small>过去三个阶段</small><b>100日胜率约63%—67%</b></span><span><small>2026真正跑赢SPY</small><b>{monthly100?.stages.forward.beat_spy_rate??"—"}% 的事件</b></span><span><small>2026平均超过SPY</small><b>{monthly100?.stages.forward.spy_excess_return??"—"}%</b></span></div><p>人话解释：月线变化很慢，刚金叉后只看20天容易看得太早。虽然2026年的平均超额收益很高，但真正跑赢SPY的事件不到一半，说明平均数被少数大涨股票明显拉高。当前只能说“值得继续研究”，还不能说“多数时候有效”。</p></section>}
   <details className="rtResearchDetails"><summary>研究人员模式：查看完整实验、样本和统计明细</summary>
   <section className="rtSystemAudit"><span><small>20日是什么意思</small><b>20个交易日＝20根日K</b></span><span><small>不是</small><b>20根周K或月K</b></span><span><small>为什么统一</small><b>便于比较不同触发周期</b></span><span><small>三段数据</small><b>2024前发现 / 2025验证 / 2026观察</b></span><mark>不是只测近3年</mark></section>
   <section className="rtExperimentOne"><header><div><small>第1次实验 · 已完成</small><h2>只有长期趋势和日线MACD金叉，结果怎样？</h2></div><mark>后续组合统一和它比较</mark></header><p className="rtExperimentPlain">一句话：20日有轻微优势，但不算强；持有100日的上涨比例更高，不过期间平均可能先跌约13%—16%，不能把它理解成“金叉后马上上涨”。</p><div className="rtExperimentHorizons">{experimentOne.map(test=><article key={test.horizon}><header><b>持有{test.horizon}个交易日</b><span>{test.horizon===20?"短期基准":"中期基准"}</span></header><div>{(Object.keys(stageMeta) as (keyof typeof stageMeta)[]).map(stage=><span key={stage}><small>{stageMeta[stage].label}</small><strong>{test.stages[stage].win_rate}%</strong><em>{test.stages[stage].samples.toLocaleString()}次</em></span>)}</div><p>{test.horizon===20?"三段胜率约53%—56%，优势存在但很薄，后续因子必须明显超过它才有价值。":"三段胜率约60%—63%，但这是更长持有期，也会受到市场长期上涨影响。"}</p></article>)}</div><footer><b>本次结论</b><span>基准建立完成，作为后续所有组合的固定比较对象。</span></footer></section>
   {experimentTwo&&<section className="rtExperimentOne rtExperimentFailed"><header><div><small>第2次实验 · 已完成</small><h2>K线经常聚集在这里，能让MACD金叉更可靠吗？</h2></div><mark>{experimentTwo.verdict}</mark></header><p className="rtExperimentPlain">一句话：不能。长期数据略好，但2025验证变差，2026的收益也没有超过简单MACD；这说明“很多K线待过”本身还不等于有效支撑。</p><div className="rtExperimentHorizons"><article><header><b>20日对比</b><span>相对第1次基准</span></header><div>{(Object.keys(stageMeta) as (keyof typeof stageMeta)[]).map(stage=><span key={stage}><small>{stageMeta[stage].label}</small><strong>{(experimentTwo.deltas[stage].win_rate??0)>0?"+":""}{experimentTwo.deltas[stage].win_rate}点</strong><em>{experimentTwo.stages[stage].samples.toLocaleString()}次</em></span>)}</div><p>胜率变化为 +1.0 / −1.0 / +0.9个百分点，方向不一致；2025稳健收益还下降0.54个百分点。</p></article><article><header><b>规则是什么</b><span>只看当时已知数据</span></header><ul><li>回看信号日前250个交易日</li><li>当前价上下3%内至少聚集15%的收盘价</li><li>从近60日高点至少回调5%</li><li>不使用成交量，避免和下次实验混在一起</li></ul></article></div><footer><b>怎么处理</b><span>不加入tracker权重，失败结果永久保留。</span></footer></section>}
   {experimentThree&&<section className="rtExperimentOne rtExperimentFailed"><header><div><small>第3次实验 · 已完成</small><h2>回到Volume Profile筹码峰，能让日线MACD更可靠吗？</h2></div><mark>{experimentThree.verdict}</mark></header><p className="rtExperimentPlain">一句话：不能。过去长期数据略有改善，但2025和2026都变差，说明这不是一个可以稳定重复的优势。</p><div className="rtExperimentHorizons"><article><header><b>20日对比</b><span>相对第1次基准</span></header><div>{(Object.keys(stageMeta) as (keyof typeof stageMeta)[]).map(stage=><span key={stage}><small>{stageMeta[stage].label}</small><strong>{(experimentThree.deltas[stage].win_rate??0)>0?"+":""}{experimentThree.deltas[stage].win_rate}点</strong><em>{experimentThree.stages[stage].samples.toLocaleString()}次</em></span>)}</div><p>胜率变化 +1.2 / −1.2 / −3.1个百分点；稳健收益变化 +0.32 / −0.29 / −0.74个百分点。</p></article><article><header><b>这次怎样识别筹码峰</b><span>日线近似版</span></header><ul><li>回看信号日前250个交易日</li><li>把价格分成40个区间，寻找成交量最大的峰</li><li>峰值至少占总成交量5%，当前价距峰值不超过3%</li><li>股价从近60日高点至少回调5%</li></ul></article></div><aside className="rtDataLimit"><b>重要限制</b><span>现有数据是日K成交量，不是逐笔或分钟级成交量，因此这里只能近似Volume Profile。它足以淘汰这条简单规则，但不能否定更精细的真实筹码分布。</span></aside><footer><b>怎么处理</b><span>不加入tracker权重，失败结果继续保留。</span></footer></section>}
   {experimentFour&&<section className="rtExperimentOne rtExperimentFailed"><header><div><small>第4次实验 · 已完成</small><h2>K线聚集和Volume Profile同时出现，会不会更可靠？</h2></div><mark>{experimentFour.verdict}</mark></header><p className="rtExperimentPlain">一句话：仍然不能。两个条件同时成立只是把样本缩小，并没有让2025和2026的结果变好。</p><div className="rtExperimentHorizons"><article><header><b>20日对比</b><span>双重筹码确认</span></header><div>{(Object.keys(stageMeta) as (keyof typeof stageMeta)[]).map(stage=><span key={stage}><small>{stageMeta[stage].label}</small><strong>{(experimentFour.deltas[stage].win_rate??0)>0?"+":""}{experimentFour.deltas[stage].win_rate}点</strong><em>{experimentFour.stages[stage].samples.toLocaleString()}次</em></span>)}</div><p>胜率变化 +1.3 / −1.8 / −2.1个百分点；2026只有245次，胜率51.4%。</p></article><article><header><b>100日结果</b><span>没有被长持有挽救</span></header><div><span><small>2024年前</small><strong>+0.2点</strong><em>17,905次</em></span><span><small>2025验证</small><strong>−3.6点</strong><em>1,625次</em></span><span><small>2026观察</small><strong>−5.7点</strong><em>245次</em></span></div><p>2026稳健收益比简单MACD少4.86个百分点，只有33.2%的事件跑赢SPY。</p></article></div><footer><b>怎么处理</b><span>双重筹码确认不加入tracker。第5次实验进入Fibonacci 0.5支撑。</span></footer></section>}
   {experimentFive&&<section className="rtExperimentOne rtExperimentFailed"><header><div><small>第5次实验 · 已完成</small><h2>回调到Fibonacci 0.5时，日线MACD会更可靠吗？</h2></div><mark>{experimentFive.verdict}</mark></header><p className="rtExperimentPlain">一句话：暂时不能。2026近期较好，但过去长期和2025验证没有同步改善。</p><div className="rtExperimentHorizons"><article><header><b>20日对比</b><span>相对简单MACD</span></header><div>{(Object.keys(stageMeta) as (keyof typeof stageMeta)[]).map(stage=><span key={stage}><small>{stageMeta[stage].label}</small><strong>{(experimentFive.deltas[stage].win_rate??0)>0?"+":""}{experimentFive.deltas[stage].win_rate}点</strong><em>{experimentFive.stages[stage].samples.toLocaleString()}次</em></span>)}</div><p>胜率变化 −0.1 / −1.7 / +1.7个百分点，三个时期方向不一致。</p></article><article><header><b>怎样确定0.5</b><span>不看未来</span></header><ul><li>只用已确认的Swing Low与后续Swing High</li><li>摆动上涨至少10%，相隔至少10个交易日</li><li>当前价距离0.5回撤位不超过2%</li><li>下一交易日开盘进入</li></ul></article></div><aside className="rtDataLimit"><b>为什么近期好也不采用？</b><span>100日增量为 −0.7 / −1.5 / +4.6个百分点。只在2026变好，不能证明它可以跨时期重复。</span></aside><footer><b>怎么处理</b><span>不加入tracker，保留为失败记录。</span></footer></section>}
   {multifactor&&<section className="rtMultiDetail"><header><div><small>第一轮多因子评分 · 完整结果</small><h2>0到6分：分数越高，结果有没有逐步变好？</h2></div><span>{multifactor.core}</span></header><div className="rtScoreTables">{multifactor.horizons.map(test=><article key={test.horizon}><h3>持有{test.horizon}个交易日</h3><div className="rtScoreHead"><span>最低分</span><span>2024前</span><span>2025</span><span>2026</span><span>结论</span></div>{test.levels.map(level=><div className="rtScoreRow" key={level.minimum_score}><b>{level.minimum_score===0?"基础":`≥${level.minimum_score}分`}</b>{(Object.keys(stageMeta) as (keyof typeof stageMeta)[]).map(stage=><span key={stage}><strong>{level.stages[stage].win_rate??"—"}%</strong><small>{level.stages[stage].samples.toLocaleString()}次</small></span>)}<mark>{level.verdict}</mark></div>)}</article>)}</div><div className="rtComponentResult"><h3>六项确认分别贡献了什么？</h3>{multifactor.contributions.map(item=>{const h=item.horizons.find(x=>x.horizon===20)!;return <article key={item.component}><b>{item.component}</b><span>{(Object.keys(stageMeta) as (keyof typeof stageMeta)[]).map(stage=><em key={stage}>{h.deltas[stage].win_rate===null?"—":`${(h.deltas[stage].win_rate??0)>0?"+":""}${h.deltas[stage].win_rate}点`}</em>)}</span><small>{item.component==="上方未补跳空缺口"?"胜率三段提高，但收益未同步，下一轮单独验证":"没有同时通过三段胜率与收益验证"}</small></article>})}</div><aside className="rtDataLimit"><b>为什么5—6分不能用？</b><span>20日达到至少5分的样本只有462 / 46 / 4次；6分只有7 / 2 / 0次。高分数字看起来漂亮，但没有足够独立样本支持。</span></aside><footer><b>本轮决策</b><span>不启用等权总分，也不把高分组合加入tracker。下一轮只保留“上方未补跳空缺口”作为有明确证据的候选，再加入价格确认做定向实验。</span></footer></section>}
   {weeklyLarge&&monthlyLarge&&<section className="rtLargeCycleDetail"><header><div><small>补充实验 · 已完成</small><h2>周线、月线金叉后，1到6个月分别怎样？</h2></div><span>每月按20个交易日</span></header>{[weeklyLarge,monthlyLarge].map(test=><article key={test.trigger}><div className="rtLargeCycleLabel"><b>{test.trigger}金叉</b><span>{test.trigger==="月线"?"越接近半年越稳定":"整体较弱"}</span></div><div className="rtLargeCycleRows">{test.horizons.map(row=><div key={row.horizon}><b>{row.horizon/20}个月</b>{(Object.keys(stageMeta) as (keyof typeof stageMeta)[]).map(stage=><span key={stage}><small>{stageMeta[stage].label}</small><strong>{row.stages[stage][test.factors[0]].win_rate}%</strong></span>)}</div>)}</div><p>{test.trigger==="月线"?`6个月样本：长期 ${largeAt(test,120,0,"development")?.samples.toLocaleString()}次，2025验证 ${largeAt(test,120,0,"validation")?.samples}次，2026观察 ${largeAt(test,120,0,"forward")?.samples}次。长期趋势过滤后的胜率是 ${largeAt(test,120,1,"development")?.win_rate}% / ${largeAt(test,120,1,"validation")?.win_rate}% / ${largeAt(test,120,1,"forward")?.win_rate}%，变化很小。`:`6个月虽然约有56%—61%的上涨率，但2026只有56.2%，且跑赢SPY和QQQ的比例不足四成。`}</p></article>)}<footer><b>聚集区结论</b><span>周线加聚集区的6个月胜率相对长期趋势基准为 −1.1 / −3.0 / +3.5个百分点；月线为 −0.3 / −10.5 / −41.3个百分点，其中2026月线聚集区只有7个完整6个月样本。方向不一致且样本不足，不采用。</span></footer></section>}
   <section className="rtTestLedger"><header><div><small>因子测试账本</small><h2>所有做过的测试，都在这里</h2></div><strong>{data.pattern_incremental_tests.length+data.incremental_tests.length}项组合已完成</strong></header><p className="rtLedgerIntro">每一项都说明“测了什么”和“为什么不能用”。不成立和不稳定的结果永久保留，不会从页面消失。</p><div className="rtLedgerHead"><span>附加因子</span><span>测试组合</span><span>结论</span></div>{data.pattern_incremental_tests.map(test=>{const a=test.deltas.development.win_rate??0,b=test.deltas.validation.win_rate??0,c=test.deltas.forward.win_rate??0;const reason=test.verdict==="不成立"?`长期段没有改善（${a>0?"+":""}${a}个百分点），收益也没有同步提高。`:`三个阶段变化为 ${a>0?"+":""}${a} / ${b>0?"+":""}${b} / ${c>0?"+":""}${c}个百分点，方向不一致。`;return <article key={test.factor}><div><b>{test.label}</b><small>{test.label==="底部Doji"||test.label==="底部Bullish Engulfing"?"底部K线形态":"价格／动量形态"}</small></div><p>长期上涨或横盘＋日线MACD金叉＋{test.label}<small>下一日开盘进入 · 持有20日</small></p><mark className={`ledger${test.verdict}`}>{test.verdict}</mark><aside><b>为什么不能用？</b><span>{reason}</span></aside></article>})}{data.incremental_tests.map(test=>{const a=test.deltas.development.win_rate??0,b=test.deltas.validation.win_rate??0,c=test.deltas.forward.win_rate??0;return <article key={test.factor}><div><b>{test.factor.replace("基准＋","")}</b><small>多周期MACD条件</small></div><p>弱市日线零轴下金叉＋{test.factor.replace("基准＋","")}<small>下一日开盘进入 · 持有20日</small></p><mark className="ledger不稳定">{test.verdict}</mark><aside><b>为什么不能用？</b><span>三个阶段胜率变化为 {a>0?"+":""}{a} / {b>0?"+":""}{b} / {c>0?"+":""}{c}个百分点，没有持续同时提高胜率和收益。</span></aside></article>})}</section>
   <section className="rtUntestedLedger"><header><div><small>尚未回测</small><h2>这些只是候选，不能当成有效因子</h2></div><span>{untestedFactors.length}项待测试</span></header><div>{untestedFactors.map(x=><article key={x}><mark>未测试</mark><b>{x}</b><small>没有历史结果，不进入tracker评分</small></article>)}</div></section>
   <details className="rtLegacyStats"><summary>查看旧版统计图表和全部原始数字</summary>
   <section className="rtSignals"><div className="rtSectionTitle"><div><p>先看这里</p><h2>目前最稳的MACD看涨组合</h2></div><span>要求三阶段为正且样本充足</span></div><div className="rtStrictGrid">{stable.slice(0,3).map((x,i)=><article key={`${x.factor}-${x.horizon}-${x.validation.regime}`}><header><mark>可继续使用 #{i+1}</mark><b>{x.factor}</b><strong>{x.horizon}日</strong></header><p>{x.validation.regime_label}</p><div className="rtEvidenceTiles"><span><small>2024年前</small><b>{x.development.win_rate}%</b></span><span><small>2025验证</small><b>{x.validation.win_rate}%</b></span><span><small>2026观察</small><b>{x.forward.win_rate}%</b></span></div><p>验证样本 {x.validation.samples.toLocaleString()} · 前向样本 {x.forward.samples.toLocaleString()}</p></article>)}</div><p className="rtRankNote">排序看三阶段中最弱的一段，而不是挑某一年最高胜率，避免把偶然好成绩放到第一名。</p></section>
   <section className="rtSignals"><div className="rtSectionTitle"><div><p>本轮增量实验</p><h2>周线、月线状态能否提升固定基准？</h2></div><span>基准：弱市＋日线零轴下金叉＋20日</span></div><p className="rtRankNote">本轮结论：没有一个附加条件在三个阶段都稳定提高胜率和收益。当前继续保留简单基准，不把周线或月线状态设为硬门槛。</p><div className="rtStrictGrid">{data.incremental_tests.map(x=><article key={x.factor}><header><mark>{x.verdict}</mark><b>{x.factor.replace("基准＋","")}</b><strong className={x.deltas.validation.win_rate>0?"":"negative"}>{x.deltas.validation.win_rate>0?"+":""}{x.deltas.validation.win_rate}%</strong></header><p>右上角是相对基准的2025胜率变化，不是该策略的绝对胜率。</p><div className="rtEvidenceTiles"><span><small>2024前增量</small><b>{x.deltas.development.win_rate>0?"+":""}{x.deltas.development.win_rate}%</b></span><span><small>2025增量</small><b>{x.deltas.validation.win_rate>0?"+":""}{x.deltas.validation.win_rate}%</b></span><span><small>2026增量</small><b>{x.deltas.forward.win_rate>0?"+":""}{x.deltas.forward.win_rate}%</b></span></div><p>2025保留基准样本的 {x.deltas.validation.sample_retention}% · 实际胜率 {x.stages.validation.win_rate}%</p></article>)}</div><p className="rtRankNote">只有三个阶段的胜率和稳健收益都提高，且验证不少于100次、前向不少于30次，才标记“有效加分”。</p></section>
   <section className="rtSignals"><div className="rtSectionTitle"><div><p>长持有期实验</p><h2>月线信号是否需要持有60—100天？</h2></div><span>20/40/60/100均为交易日</span></div><div className="rtChartGrid">{data.monthly_horizon_tests.map(test=><article className="rtChartCard" key={test.factor}><header><div><mark>月线实验</mark><h3>{test.label}</h3></div><small>{test.horizons[0].stages.validation.samples}个2025样本</small></header><WinRateChart test={test}/><footer>{test.factor==="基准＋月线准备金叉"?"样本过少，只观察，不下结论":test.factor==="月线零轴下金叉"?"100日三阶段：63.3% / 65.3% / 67.1%":"100日并未稳定超过同环境的简单日线基准"}</footer></article>)}</div><div className="rtResearchVerdict"><b>验证后的准确说法</b><p>月线自身刚金叉，从20日拉长至100日后表现明显更一致；但把“月线已经多头”加到弱市日线金叉上，100日相对简单日线基准仅为 <strong>+1.2 / +0.4 / −0.5个百分点</strong>，不能称为显著加分。</p></div><p className="rtRankNote">长周期事件大量重叠，而且美股长期向上会自然推高原始胜率；下一轮还要加入相对SPY/QQQ的超额收益曲线。</p></section>
   <section className="rtSignals"><div className="rtSectionTitle"><div><p>周期单独测试</p><h2>日线、周线、月线零轴下金叉</h2></div><span>按三阶段平均胜率选择固定持有期</span></div><div className="rtModuleGrid">{baselines.map(x=><article key={x.factor}><small>{x.factor} · 当前最稳健窗口</small><h2>{x.horizon}个交易日</h2><p>2024年前 {x.development.win_rate}% · {x.development.samples.toLocaleString()}样本<br/>2025验证 {x.validation.win_rate}% · {x.validation.samples.toLocaleString()}样本<br/>2026观察 {x.forward.win_rate}% · {x.forward.samples.toLocaleString()}样本</p><strong>验证期稳健均值 {x.validation.trimmed_mean_return}% · 中位数 {x.validation.median_return}%</strong></article>)}</div><p className="rtRankNote">当前三个周期都以20个交易日最稳定。周线金叉的5日和10日表现没有通过2025验证；月线信号较强，但样本远少于日线，不能仅凭单年高胜率提高过多权重。</p></section>
   <details className="rtSignals"><summary>查看更多组合的原始统计</summary><div className="rtMatrix"><div className="rtMatrixHead"><span>策略</span><span>市场环境</span><span>2025验证</span><span>2026观察</span><span>结论</span></div>{stable.map((x,i)=><div className="rtMatrixRow" key={`${x.factor}-${x.horizon}-${x.validation.regime}`}><div className="rtMatrixTicker"><em>{i+1}</em><b>{x.factor}</b><small>持有{x.horizon}日</small></div><div className="rtLayerCell buy"><b>{x.validation.regime_label}</b><small>固定环境</small></div><div className="rtLayerCell buy"><b>{x.validation.win_rate}%</b><small>{x.validation.samples.toLocaleString()}样本</small></div><div className="rtLayerCell buy"><b>{x.forward.win_rate}%</b><small>{x.forward.samples.toLocaleString()}样本</small></div><div className="rtMatrixVerdict buy"><b>继续保留</b><small>研究结论</small></div></div>)}</div><p className="rtMethod">{data.execution}。{data.lookahead}。{data.warning}</p></details>
   </details>
   </details>
  </>}
 </TrackerShell>
}
