"use client";
import {useEffect,useState} from "react";
import {TrackerShell} from "../tracker-ui";
import {EmptyState,MetricCard,SectionHeader,StatusBadge} from "../product-ui";
type Tab="backtest"|"forward"|"experiments";
type DailyState={date:string;in_current_opportunities:boolean;legacy_production_score:number|null;official_score:number|null;experimental_observational_score:number|null};
type Case={signal_id:string;symbol:string;first_seen_date:string;source_systems:string[];lifecycle:string;latest_current_status:string;daily_states?:DailyState[];signal_time_snapshot:{technical:{tracker_rank:number|null;technical_score:number|null};multi_factor:{official_score:number|null;experimental_observational_score:number|null};industry:{themes:{name:string;state:string}[]}};forward:{returns:Record<string,number|null>;mfe:number|null;mae:number|null;status:string}};
type History={as_of:string;future_data_used:boolean;cases:Case[]};
type Backtest={universe:{eligible:number;events:number;history_earliest:string;history_latest:string};warning:string};
type Experiment={experiment_id:string;status:string;change:string;coverage?:string;result:string;known_limitations?:string[]};
type Catalog={experiment_count:number;experiments:Experiment[];missing_registry_references:string[]};
type DecisionItem={name:string;role?:string;verdict:string;metrics:{samples:number;win_rate:number;profit_factor:number;expectancy_pct:number};note:string};
type Decision={plain_summary:string;usable:DecisionItem[];avoid:DecisionItem[]};
type FactorResult={factor:string;research_status:string;action:string;tone:string;samples_2026:number;win_rate_2026:number;profit_factor_2026:number;expectancy_2026:number};
type Effectiveness={coverage:{source_signals_end:string};warning:string;factors:FactorResult[]};
const studies=[
 ["Tracker Backtest","V1","2010—2026","11,896 signals","PF 1.122 · win rate 52.95%","/zh/watch/resonance/strategy-backtest","Validated / Keep"],
 ["Stop Loss / Risk-Reward","V2","2010—2026","Tracker samples","PF 1.178 · expectancy +0.801%","/zh/watch/resonance/strategy-backtest-v2","Candidate"],
 ["Market Regime","V1","Point-in-time","Long benchmark","未验证","/zh/watch/resonance/market-regime","Rejected"],
 ["Factor Attribution","V1","Walk-forward","Factor samples","已完成","/zh/watch/resonance/factor-attribution","Validated / Keep"],
 ["Ranking Research","V1","Walk-forward","Shared candidate pool","未验证","/zh/watch/resonance/ranking-research","Rejected"],
 ["Stock Selection","V1","Walk-forward","Leadership vs Pullback","未验证","/zh/watch/resonance/selection-research","Rejected"],
] as const;
const fmt=(v:number|null)=>v===null?"Pending":`${v>=0?"+":""}${(v*100).toFixed(2)}%`;
export default function Research(){
 const [tab,setTab]=useState<Tab>(()=>{if(typeof window==="undefined")return "backtest";const value=new URLSearchParams(window.location.search).get("tab");return value==="forward"||value==="experiments"?value:"backtest"}),[history,setHistory]=useState<History|null>(null),[backtest,setBacktest]=useState<Backtest|null>(null),[catalog,setCatalog]=useState<Catalog|null>(null),[decision,setDecision]=useState<Decision|null>(null),[effectiveness,setEffectiveness]=useState<Effectiveness|null>(null);
 useEffect(()=>{fetch("/signal-history.json",{cache:"no-store"}).then(x=>x.ok?x.json():null).then(setHistory);fetch("/macd-factor-backtest.json").then(x=>x.json()).then(setBacktest);fetch("/experiment-catalog.json",{cache:"no-store"}).then(x=>x.ok?x.json():null).then(setCatalog);fetch("/decision-summary.json",{cache:"no-store"}).then(x=>x.ok?x.json():null).then(setDecision);fetch("/factor-effectiveness.json",{cache:"no-store"}).then(x=>x.ok?x.json():null).then(setEffectiveness)},[]);
 const active=history?.cases.filter(x=>x.latest_current_status==="current").length??0,matured=history?.cases.filter(x=>x.lifecycle==="MATURED").length??0,technical=history?.cases.filter(x=>x.source_systems.includes("technical_tracker")).length??0,multi=history?.cases.filter(x=>x.source_systems.includes("multi_factor_radar")).length??0;
 return <TrackerShell active="研究 / 实验" title="研究 / 实验" subtitle="历史重建、真实 Forward Observation 与实验结论各自独立。"><div className="researchV2">
  <nav className="researchTabs" aria-label="研究类型"><button className={tab==="backtest"?"active":""} onClick={()=>setTab("backtest")}>Backtesting</button><button className={tab==="forward"?"active":""} onClick={()=>setTab("forward")}>Forward Testing</button><button className={tab==="experiments"?"active":""} onClick={()=>setTab("experiments")}>Experiments</button></nav>
  {tab==="backtest"&&<><section className="researchMetrics"><MetricCard label="历史范围" value={backtest?`${backtest.universe.history_earliest.slice(0,4)}—${backtest.universe.history_latest.slice(0,4)}`:"—"}/><MetricCard label="合格股票" value={backtest?.universe.eligible.toLocaleString()??"—"}/><MetricCard label="MACD 事件" value={backtest?.universe.events.toLocaleString()??"—"}/><MetricCard label="当前研究基准" value="PF 1.178" detail="Expectancy +0.801%" tone="positive"/></section><section className="svPanel"><SectionHeader eyebrow="HISTORICAL RECONSTRUCTION" title="Backtesting" description="先看范围、样本与关键结果；每项详细统计在独立研究页。"/><div className="studyGrid">{studies.map(s=><article key={s[0]}><header><StatusBadge state={s[6]}>{s[6]}</StatusBadge><small>{s[1]}</small></header><h3>{s[0]}</h3><p>{s[2]} · {s[3]}</p><strong>{s[4]}</strong><a href={s[5]}>查看完整结果 →</a></article>)}</div></section></>}
  {tab==="forward"&&<><section className="researchMetrics"><MetricCard label="Active cases" value={active} tone="positive"/><MetricCard label="Matured cases" value={matured}/><MetricCard label="Technical Tracker" value={technical}/><MetricCard label="Multi-Factor" value={multi}/></section><section className="svPanel"><SectionHeader eyebrow="PERMANENT TRACKING POOL" title="Forward Testing" description="首次触发永久保留；当前掉榜只改变状态，不删除案例。历史回测与真实 Forward 分别统计。"/><div className="forwardTable"><div className="forwardRow forwardHead"><span>Ticker</span><span>First Seen</span><span>Source</span><span>Original Rank / Score</span><span>Latest Old / 27F</span><span>Status</span><span>+1D</span><span>+5D</span><span>+20D</span><span>+100D</span><span>MFE</span><span>MAE</span></div>{history?.cases.map(x=>{const latest=x.daily_states?.at(-1);return <article className="forwardRow" key={x.signal_id}><b>{x.symbol}</b><span>{x.first_seen_date}</span><span>{x.source_systems.join(" + ")}</span><span>{x.signal_time_snapshot.technical.tracker_rank?`#${x.signal_time_snapshot.technical.tracker_rank}`:"—"} / {x.signal_time_snapshot.technical.technical_score??x.signal_time_snapshot.multi_factor.experimental_observational_score??"—"}</span><span>{latest?`${latest.legacy_production_score??"—"} / ${latest.experimental_observational_score??"—"}`:"等待下一次EOD"}</span><StatusBadge state={x.latest_current_status}>{x.latest_current_status}</StatusBadge><span>{fmt(x.forward.returns["1"])}</span><span>{fmt(x.forward.returns["5"])}</span><span>{fmt(x.forward.returns["20"])}</span><span>{fmt(x.forward.returns["100"])}</span><span>{fmt(x.forward.mfe)}</span><span>{fmt(x.forward.mae)}</span></article>})}</div>{!history?.cases.length&&<EmptyState title="尚无 production_forward case"/>}<footer className="researchAudit">数据截至 {history?.as_of??"—"} · future_data_used={String(history?.future_data_used??"waiting")}</footer></section></>}
  {tab==="experiments"&&<><section className="svPanel"><SectionHeader eyebrow="WHAT CAN I USE" title="实验结论：现在怎么用" description={decision?.plain_summary??"正在整理可执行结论。"}/><div className="experimentLedger practical">{decision?.usable.map(x=><article key={x.name}><header><b>{x.name}</b><StatusBadge state="keep">{x.verdict}</StatusBadge></header><p><b>做什么：</b>{x.role}</p><strong>胜率 {x.metrics.win_rate.toFixed(1)}% · PF {x.metrics.profit_factor.toFixed(2)} · 期望 {x.metrics.expectancy_pct>0?"+":""}{x.metrics.expectancy_pct.toFixed(2)}%</strong><small><b>怎么用：</b>{x.note}</small><small>样本 {x.metrics.samples}</small></article>)}</div><h3 className="experimentSubhead">不要这样用</h3><div className="experimentLedger practical avoid">{decision?.avoid.map(x=><article key={x.name}><header><b>{x.name}</b><StatusBadge state="rejected">{x.verdict}</StatusBadge></header><strong>胜率 {x.metrics.win_rate.toFixed(1)}% · PF {x.metrics.profit_factor.toFixed(2)} · 期望 {x.metrics.expectancy_pct.toFixed(2)}%</strong><small><b>原因：</b>{x.note}</small><small>样本 {x.metrics.samples}</small></article>)}</div>{!decision&&<EmptyState title="实验结论尚未生成"/>}</section><section className="svPanel"><SectionHeader eyebrow="FACTOR DECISIONS" title="每个因子该怎么处理" description={`截至 ${effectiveness?.coverage.source_signals_end??"—"}；只看结论和用法，详细账本放在下方。`}/><div className="factorDecisionTable"><div><b>因子</b><b>结果</b><b>胜率 / PF</b><b>实际处理</b></div>{effectiveness?.factors.map(x=><div key={x.factor}><b>{x.factor}</b><span>{x.research_status}</span><span>{x.win_rate_2026.toFixed(1)}% / {x.profit_factor_2026.toFixed(2)}</span><strong>{x.action}</strong></div>)}</div><p className="researchAudit">{effectiveness?.warning}</p><details className="rawLedger"><summary>查看完整实验审计账本（{catalog?.experiment_count??"—"} 项）</summary><div className="experimentLedger">{catalog?.experiments.map(x=><article key={x.experiment_id}><header><b>{x.experiment_id}</b><StatusBadge state={x.status}>{x.status}</StatusBadge></header><p>{x.change}</p><strong>{x.result}</strong></article>)}</div></details></section></>}
 </div></TrackerShell>
}
