"use client";
import {useEffect,useMemo,useState} from "react";
type Metric={factor:string;horizon:number;dates:number;observations:number;mean_ic:number|null;ic_positive_pct:number|null;spread:number|null};
type Report={coverage:{symbols_requested:number;symbols_loaded:number;eligible_latest:number;panel_rows:number;snapshot_dates:number};version:string;walk_forward:Record<string,{start:string;end:string}>;factors:{implemented:{id:string;plain:string}[];missing:string[]};split_metrics:Record<string,Metric[]>;factor_verdicts:{factor:string;verdict:string}[];redundancy:{a:string;b:string;mean_rank_correlation:number|null}[];data_standard:{required:string[]};experiment:{id:string};interpretation:string};
const pct=(x:number|null)=>x===null?"—":`${(x*100).toFixed(2)}%`;
const names:Record<string,string>={momentum_12_1:"12–1 momentum",momentum_6_1:"6–1 momentum",momentum_3_1:"3–1 momentum",trend_quality:"Trend quality",low_volatility:"Low volatility",liquidity:"Liquidity"};
export default function ResearchLab(){
 const [r,setR]=useState<Report|null>(null),[h,setH]=useState(60),[sample,setSample]=useState("validation");
 useEffect(()=>{fetch("/research-report.json").then(x=>x.json()).then(setR)},[]);
 const rows=useMemo(()=>r?.split_metrics[sample]?.filter(x=>x.horizon===h).sort((a,b)=>(b.mean_ic??-9)-(a.mean_ic??-9))??[],[r,h,sample]);
 if(!r)return <main className="researchlab"><p>Loading research evidence…</p></main>;
 return <main className="researchlab"><header className="researchhead"><p>NORTHSTAR / FACTOR LAB</p><h1>Evidence before conviction.</h1><span>Signals are tested alone, on untouched data, before combination. This page does not issue trades.</span></header>
 <section className="coverage"><div><small>SYMBOLS LOADED</small><b>{r.coverage.symbols_loaded}</b><span>of {r.coverage.symbols_requested} requested</span></div><div><small>ELIGIBLE NOW</small><b>{r.coverage.eligible_latest}</b><span>price, liquidity and history gate</span></div><div><small>STOCK SNAPSHOTS</small><b>{r.coverage.panel_rows.toLocaleString()}</b><span>{r.coverage.snapshot_dates} month-end dates</span></div><div><small>RESEARCH VERSION</small><b>{r.version}</b><span>{r.experiment.id}</span></div></section>
 <section className="samplebar"><span>Evidence sample</span>{Object.keys(r.split_metrics).map(x=><button className={sample===x?"active":""} onClick={()=>setSample(x)} key={x}>{x.replace("_"," ")}</button>)}</section>
 <section className="researchgrid"><article><div className="research-title"><div><p className="label">SINGLE-FACTOR RESULTS</p><h2>Does each factor survive unseen data?</h2></div><div className="horizons">{[5,10,20,60].map(x=><button className={h===x?"active":""} onClick={()=>setH(x)} key={x}>{x}D</button>)}</div></div>
 <div className="metric-head robust"><span>Factor</span><span>Verdict</span><span>Mean IC</span><span>Positive IC</span><span>Top–bottom</span><span>Observations</span></div>{rows.map(x=>{const verdict=h===60?r.factor_verdicts.find(v=>v.factor===x.factor)?.verdict:"60D only";return <div className="metric-row robust" key={x.factor}><div><b>{names[x.factor]??x.factor}</b><small>{r.factors.implemented.find(f=>f.id===x.factor)?.plain}</small></div><span className={`verdict ${verdict}`}>{verdict}</span><strong className={(x.mean_ic??0)>0?"positive":"negative"}>{x.mean_ic?.toFixed(3)??"—"}</strong><span>{x.ic_positive_pct?.toFixed(1)??"—"}%</span><span className={(x.spread??0)>0?"positive":"negative"}>{pct(x.spread)}</span><span>{x.observations.toLocaleString()}</span></div>})}<p className="research-note">{r.interpretation}</p></article>
 <aside><p className="label">WALK-FORWARD BOUNDARIES</p>{Object.entries(r.walk_forward).map(([k,v])=><div className="split" key={k}><b>{k.replace("_"," ")}</b><span>{v.start} → {v.end}</span></div>)}<p className="label blockers">KNOWN BLOCKERS</p><ul>{r.factors.missing.map(x=><li key={x}>{x}</li>)}</ul></aside></section>
 <section className="evidencegrid"><article><p className="label">REDUNDANCY CHECK</p><h2>Agreement is not independence.</h2><p>The strongest overlaps warn us when two indicators are mostly repeating the same information.</p>{r.redundancy.slice(0,5).map(x=><div className="correlation" key={`${x.a}-${x.b}`}><span>{names[x.a]} ↔ {names[x.b]}</span><b>{x.mean_rank_correlation?.toFixed(2)}</b></div>)}</article><article><p className="label">DATA CONTRACT</p><h2>What trustworthy history must contain.</h2><ul>{r.data_standard.required.map(x=><li key={x}>{x}</li>)}</ul></article></section>
 <section className="pipeline"><p className="label">GROWING PROGRAM</p><div><article><b>01</b><h3>Freeze data</h3><p>Every observation carries an as-of date, source and calculation version.</p></article><article><b>02</b><h3>Test alone</h3><p>Measure predictive strength, decay and stability for each factor separately.</p></article><article><b>03</b><h3>Combine carefully</h3><p>Only complementary validated factors become a challenger strategy.</p></article><article><b>04</b><h3>Forward test</h3><p>Publish immutable paper decisions before observing their outcomes.</p></article></div></section></main>;
}
