"use client";
import {useEffect,useRef} from "react";
import {TrackerShell} from "../tracker-ui";
import report from "../../../../../research/backtest/output/summary.json";

type Metric={samples:number;win_rate:number|null;average_return:number|null;median_return:number|null;profit_factor:number|null;expectancy:number|null;stop_out_rate:number|null;mfe:number|null;mae:number|null;max_drawdown:number|null};
const pct=(x:number|null)=>x===null?"—":`${x.toFixed(2)}%`;
function Curve({kind}:{kind:"equity"|"drawdown"}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const draw=()=>{const d=report.curves as {date:string;equity:number;drawdown:number}[],box=canvas.getBoundingClientRect(),scale=devicePixelRatio||1;canvas.width=box.width*scale;canvas.height=box.height*scale;const c=canvas.getContext("2d");if(!c||!d.length)return;c.scale(scale,scale);const w=box.width,h=box.height,p=28,vals=d.map(x=>kind==="equity"?x.equity:x.drawdown),lo=Math.min(...vals),hi=Math.max(...vals),range=hi-lo||1;c.clearRect(0,0,w,h);c.strokeStyle="#e1e6ed";c.lineWidth=1;for(let i=0;i<4;i++){const y=p+i*(h-p*2)/3;c.beginPath();c.moveTo(p,y);c.lineTo(w-p,y);c.stroke()}c.strokeStyle=kind==="equity"?"#526f9d":"#ad655f";c.lineWidth=2;c.beginPath();d.forEach((x,i)=>{const xx=p+i*(w-p*2)/(d.length-1),v=kind==="equity"?x.equity:x.drawdown,yy=p+(hi-v)*(h-p*2)/range;i?c.lineTo(xx,yy):c.moveTo(xx,yy)});c.stroke();c.fillStyle="#68758a";c.font="10px sans-serif";c.fillText(d[0].date,p,h-7);c.textAlign="right";c.fillText(d.at(-1)?.date??"",w-p,h-7);c.textAlign="left"};draw();const ro=new ResizeObserver(draw);ro.observe(canvas);return()=>ro.disconnect()},[kind]);return <canvas ref={ref} className="btCurve" aria-label={kind==="equity"?"非重叠等权信号组权益曲线":"非重叠等权信号组回撤曲线"}/>}
function MetricRow({name,x}:{name:string;x:Metric}){return <div className="btMetricRow"><b>{name}</b><span>{x.samples.toLocaleString()}</span><span>{pct(x.win_rate)}</span><span>{pct(x.average_return)}</span><span>{x.profit_factor?.toFixed(3)??"—"}</span><span>{pct(x.stop_out_rate)}</span><span>{pct(x.mae)}</span></div>}
export default function StrategyBacktest(){const status=report.comparisons.filter(x=>x.dimension==="status") as Metric[]&{group:string}[],trend=report.comparisons.filter(x=>x.dimension==="trend") as Metric[]&{group:string}[];return <TrackerShell active="Strategy Backtest" title="Strategy Backtest / 策略回测" subtitle="Tracker Backtest V1 · 独立研究层，不进入生产排名、网站 Tracker 或 Discord。">
 <section className="btNotice"><b>V1 结论：有很薄的20日正优势，但远未达到可交易策略标准。</b><span>2010-01-05 至 2026-06-24 · {report.sample.signals.toLocaleString()} 个历史 Top 10 Long 信号 · 下一交易日 Open 入场</span></section>
 <section className="btAnswers"><article><small>历史上有没有 edge？</small><b>有，但很薄</b><p>20日平均 {pct(report.overall_by_horizon["20"].average_return)}，Profit Factor {report.overall_by_horizon["20"].profit_factor}。</p></article><article><small>胜率超过50%？</small><b>{pct(report.overall_by_horizon["20"].win_rate)}</b><p>5日只有 {pct(report.overall_by_horizon["5"].win_rate)}，优势主要在更长窗口。</p></article><article><small>高排名更好吗？</small><b>不是</b><p>排名1–3平均 {pct(report.ranking_buckets[0].average_return)}，7–10反而为 {pct(report.ranking_buckets[2].average_return)}。</p></article><article><small>高分更好吗？</small><b>总体单调，但需验证</b><p>0–2分 {pct(report.score_buckets[0].average_return)}；5+分 {pct(report.score_buckets[2].average_return)}。</p></article><article><small>长期趋势过滤？</small><b>温和改善</b><p>胜率 51.34% → 52.95%，但2025过滤组平均收益仍为负。</p></article><article><small>Early vs Confirmed</small><b>Confirmed 总体较好</b><p>平均收益 0.475% vs 0.200%；2026则 Early Watch 更好，尚不稳定。</p></article></section>
 <section className="btPanel"><header><div><small>CORE STATISTICS · 20D</small><h2>状态与长期趋势过滤</h2></div><span>原始 forward return，不做参数优化</span></header><div className="btMetricHead"><b>组别</b><span>样本</span><span>胜率</span><span>平均收益</span><span>PF</span><span>止损率</span><span>MAE</span></div>{status.map((x:any)=><MetricRow key={x.group} name={x.group} x={x}/>)}{trend.map((x:any)=><MetricRow key={x.group} name={x.group.replace("Control · ","")} x={x}/>)}</section>
 <section className="btGrid"><article className="btPanel"><header><div><small>RANK MONOTONICITY</small><h2>排名越高，没有越好</h2></div></header>{report.ranking_buckets.map(x=><div className="btBar" key={x.bucket}><b>Rank {x.bucket}</b><i><em style={{width:`${Math.max(4,Math.abs(x.average_return??0)/.7*100)}%`}}/></i><span>{pct(x.average_return)} · {pct(x.win_rate)}</span></div>)}</article><article className="btPanel"><header><div><small>SCORE MONOTONICITY</small><h2>总分出现正向梯度</h2></div></header>{report.score_buckets.map(x=><div className="btBar" key={x.bucket}><b>Score {x.bucket}</b><i><em style={{width:`${Math.max(4,Math.abs(x.average_return??0)/1.1*100)}%`}}/></i><span>{pct(x.average_return)} · n={x.samples}</span></div>)}<p className="btCaution">3–4分只有 {report.score_buckets[1].samples} 个样本；不能据此修改 production 权重。</p></article></section>
 <section className="btPanel"><header><div><small>STOP BUFFER · SUPPORT LEVEL</small><h2>Support −1% 止损过于频繁</h2></div><span>只比较，不选择最佳参数</span></header><div className="btStopGrid">{report.stop_buffers.map(x=><article key={x.buffer_pct}><small>Support −{x.buffer_pct}%</small><b>{pct(x.stop_out_rate)}</b><span>Stop-out</span><p>20D stop-adjusted {pct(x.average_return)}<br/>PF {x.profit_factor}</p></article>)}</div><p className="btCaution">1% buffer 的止损率为 {pct(report.stop_buffers[0].stop_out_rate)}。这说明 support 定义或日线波动容忍度是 V1 最明显的问题之一；本页不自动选择 2%、3% 或 5%。</p></section>
 <section className="btGrid"><article className="btPanel"><header><div><small>NON-OVERLAPPING COHORTS</small><h2>Equity Curve</h2></div></header><Curve kind="equity"/></article><article className="btPanel"><header><div><small>DIAGNOSTIC DRAWDOWN</small><h2>Drawdown Curve</h2></div></header><Curve kind="drawdown"/></article></section>
 <section className="btPanel"><header><div><small>FIXED TAKE PROFIT</small><h2>1R / 2R / 3R 风险收益结构</h2></div><span>默认 Support −1% · 40D上限</span></header><div className="btRGrid">{report.r_targets.map(x=><article key={x.target_r}><b>{x.target_r}R</b><span>目标命中 {pct(x.target_hit_rate)}</span><strong>平均 {x.average_r}R</strong><small>中位 {x.median_r}R · n={x.samples.toLocaleString()}</small></article>)}</div></section>
 <section className="btPanel btHistory"><header><div><small>HISTORICAL SIGNALS</small><h2>最近历史信号</h2></div><span>完整账本保存在 research/backtest/output/signals.jsonl</span></header><div className="btTable"><div className="btTableHead"><span>日期</span><span>Ticker</span><span>状态</span><span>排名</span><span>总分</span><span>趋势</span><span>Support</span><span>20D</span></div>{report.historical_signals.slice(0,100).map(x=><div key={`${x.date}-${x.ticker}`}><span>{x.date}</span><b>{x.ticker}</b><span>{x.status}</span><span>#{x.tracker_ranking}</span><span>{x.multi_factor_total_score}</span><span>{x.strict_long_trend?"Pass":"Control"}</span><span>{x.support_level?.toFixed(2)??"—"}</span><strong className={(x.forward_returns["20"]??0)>=0?"positive":"negative"}>{pct((x.forward_returns["20"]??0)*100)}</strong></div>)}</div></section>
 <section className="btLimits"><b>V1 最明显的问题</b><p>排名没有形成单调关系；1% support buffer 止损过于频繁；信号重叠且没有资金约束；历史 universe 不是完整美股，退市与换代码覆盖仍不完整。最大回撤来自非重叠等权信号组诊断，不应视为可执行组合回撤。</p>{report.limitations.map(x=><span key={x}>{x}</span>)}</section>
 </TrackerShell>}
